<?php 
 	$store_currency = $this->getChildHtml("store_currency2");
 	$store_language = $this->getChildHtml("store_language2");
 	$store_links = $this->getChildHtml("store_links2");
 	$menu_top = $this->getChildHtml("menu_top2");
?>
<div class="sections nav-sections">
	<div class="section-items nav-sections-items" data-mage-init='{"tabs":{"openedState":"active"}}'>
		<?php if($menu_top): ?>
		<div class="section-item-title nav-sections-item-title hidden-lg hidden-md" data-role="collapsible" role="tablist" aria-controls="store.top.menu2"><a class="nav-sections-item-switch" href="#store.menu2"><?php echo __('Menu3'); ?></a></div>
		<?php endif; ?>
		<?php if($store_links): ?>
		<div class="section-item-title nav-sections-item-title hidden-lg hidden-md" data-role="collapsible" role="tablist" aria-controls="store.account2"><a class="nav-sections-item-switch" href="#store.menu2"><?php echo __('Account'); ?></a></div>
		<?php endif; ?>
		<?php if($store_currency || $store_language): ?>
		<div class="section-item-title nav-sections-item-title hidden-lg hidden-md" data-role="collapsible" role="tablist" aria-controls="store.settings2"><a class="nav-sections-item-switch" href="#store.menu2"><?php echo __('Settings'); ?></a></div>
		<?php endif; ?>
		<?php if($menu_top): ?>
		<div class="section-item-content" id="store.top.menu2" data-role="content" role="tabpanel">
			<?php echo $menu_top; ?>
		</div>
		<?php endif; ?>
		<?php if($store_links): ?>
		<div class="section-item-content hidden-lg hidden-md" id="store.account2" data-role="content" role="tabpanel">
			<?php echo $this->getChildHtml("store_links2"); ?>
		</div>
		<?php endif; ?>
		<?php if($store_currency || $store_language): ?>
		<div class="section-item-content hidden-lg hidden-md" id="store.settings2" data-role="content" role="tabpanel">
			<?php echo $this->getChildHtml("store_currency2"); ?>
			<?php echo $this->getChildHtml("store_language2"); ?>
		</div>
		<?php endif; ?>
	</div>
</div>