<?php
$ves = $this->helper('Ves\Themesettings\Helper\Theme');
$sticky = $ves->getHeaderCfg("sticky_settings/sticky");
$sticky_type = $ves->getHeaderCfg("sticky_settings/sticky_type");
$logo = $ves->getHeaderCfg("sticky_settings/logo");
$menu = $ves->getHeaderCfg("sticky_settings/menu");
$search = $ves->getHeaderCfg("sticky_settings/search");
$custom_block = $ves->getHeaderCfg("sticky_settings/custom_block");
$topcart = $ves->getHeaderCfg("sticky_settings/topcart");
$topbar = $ves->getHeaderCfg("sticky_settings/topbar");
$enable_toplinks = $ves->getHeaderCfg("toplinks_settings/enable");
$show_search = $ves->getHeaderCfg("search_settings/search");
$show_topbar = $ves->getHeaderCfg("topbar/show_topbar");

if($sticky_type == 'all'){
	$logo = $menu = $search = $topcart = $toplinks = $topbar= true;	
}
?>
<div id="ves-header" class="header header-style-6">
	<!-- Top bar -->
	<?php if($show_topbar): ?>
	<div class="panel wrapper page-topbar d-none d-lg-block clearfix <?php echo $topbar?"sticky-item":"sticky-item-hidden"?>">
		<div class="container">
			<div class="ves-inner">
				<div class="row">
					<div class="col-sm-7 col-md-8 col-lg-8">
						<div class="f-left top-left-link">
							<div class="text-welcome">
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-welcome')->toHtml();?>
							</div>
						</div>
					</div>
					<div class="col-sm-5 col-md-4 col-lg-4">
						<div class="f-right">
							<?php echo $this->getChildHtml('setting_links') ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<?php endif; ?>
	
	<!-- header content -->
	<div class="header-content clearfix">
		<div class="container">
			<div class="ves-inner">
			<div class="grid-wrap">
				<div class="grid-col md-25 header-logo-block" style="width: 20%;">
					<div class="logo-wrapper <?php echo $logo?"sticky-item":"sticky-item-hidden"  ?>">
						<?php echo $this->getChildHtml('logo') ?>
					</div>
				</div>
				<div class="grid-col md-55 header-search-block" style="width: 60%;">
					<div class="search-wrapper ves-autosearch mobile-account-link hidden-lg hidden-sm hidden-md">
						<a class="mobile-link-account" href="<?= $this->getUrl("customer/account/"); ?>">
							<i class="icon icon-342">&nbsp;</i>
						</a>
					</div>
					<?php if($show_search): ?>
						<div class="search-wrapper ves-autosearch">
							<div class="d-toggle d-lg-none" data-toggle="dropdown">
								<i class="icon icon-1202">&nbsp;</i>
							</div>
							<div class="search-content" role="menu">
								<?php echo $this->getChildHtml('ves_autosearch') ?>
							</div> 
						</div>
					<?php endif; ?>
				</div>
				<div class="grid-col header-user-link" style="width: 20%;">
					<div class="user f-right d-none d-lg-block">
						<?php
							$objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
							$customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
							$baseurl = $objectManagerlogin->get('Magento\Store\Model\StoreManagerInterface')->getStore(0)->getBaseUrl();
							if($customerSession->isLoggedIn()) { ?>
								<?php echo $this->getChildHtml('top_links') ?>
							<?php }
							else{
								?>
							    <i class="icon icon-342">&nbsp;</i>
							    <div class="link-account">
								    <a href="<?php echo $this->getUrl('customer/account/login/');?>"><?php echo __("Log in");?></a>
								    <a href="<?php echo $this->getUrl('customer/account/create/');?>"><?php echo __("Register");?></a>
							    </div>
						<?php
							}
						?>
					</div>
					<div class="minicart-warp <?php echo $topcart?"sticky-item":"sticky-item-hidden"  ?>">
						<?php echo $this->getChildHtml('minicart') ?>
					</div>
				</div>
				<?php if($custom_block = $this->getChildHtml("custom_block")): ?>
				<div class="customblock-wrapper <?php echo $custom_block?"sticky-item":"sticky-item-hidden"  ?>">
					<?php echo $custom_block; ?>
				</div>
				<?php endif; ?>
			</div>
			</div>
		</div>
	</div>
	<div class="header-menu">
		<div class="container">
			<div class="grid-wrap">
				<div class="grid-col md-25" style="width: 20%;">
					<!-- Menu top -->
					<div class="ves-menutop dropdown clearfix <?php echo $menu?"sticky-item":"sticky-item-hidden" ?>">
						<div class="dropdown-toggle d-none d-lg-block" data-toggle="dropdown">
							<span class="icon icon-1178">&nbsp;</span><span class="menu-title"><?php echo __("Shop by Department");?></span>
						</div>
						<div class="dropdown-content">
							<?php echo $this->getChildHtml('catalog.topnav') ?>
						</div>
					</div>
				</div>
				<div class="grid-col md-75 d-none d-lg-block" style="width: 80%;">
				<?php
					$horizontal_menu = $this->getChildHtml('ves_horizontal_menu');
				?>
					<?php echo $horizontal_menu?$horizontal_menu:$block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('menu-links')->toHtml();?>
				</div>
			</div>
		</div>
	</div>

	<?php if($sticky){ ?>
	<script type="text/javascript">
		require([
			'jquery',
			'Ves_Themesettings/js/theme'
			], function(){
				
				function getScroll () {
				    var b = document.body;
				    var e = document.documentElement;
				    return {
				        left: parseFloat( window.pageXOffset || b.scrollLeft || e.scrollLeft ),
				        top: parseFloat( window.pageYOffset || b.scrollTop || e.scrollTop )
				    };
				}
				jQuery(document).ready(function($) {
					var h = jQuery('.page-header').height();
					var myHeader = jQuery('.page-header');
					var hasBreadcrumbs = false;
					var breadcrumbs = jQuery(".breadcrumbs");
					if(typeof(breadcrumbs) != "undefined" && breadcrumbs.length > 0) {
						hasBreadcrumbs = true;
					}
					myHeader.data( 'position', myHeader.position() );

					jQuery(window).scroll(function(){
						var hPos = myHeader.data('position'), scroll = getScroll();
						var h_px = jQuery("#ves-header", ".page-header").outerHeight(true)+"px";

						if ( hPos.top < scroll.top) {
							jQuery('.page-header').addClass("navbar-fixed-top keep-header");
							var headerHeight = jQuery('.page-header').height();
							<?php if($sticky_type == 'specify'){ ?>jQuery(".page-wrapper").css({"padding-top":headerHeight+"px"});<?php } ?>
							jQuery(".sticky-item-hidden").css({"display":"none"});
							if(!hasBreadcrumbs) {
								jQuery("#maincontent").delay(1000).css("margin-top", h_px);
							}
						}else{
							jQuery(".sticky-item-hidden").css({"display":""});
							jQuery('.page-header').removeClass("navbar-fixed-top keep-header");
							jQuery(".page-wrapper").css({"padding-top":""});
							if(!hasBreadcrumbs) {
								jQuery("#maincontent").delay(1000).css({"margin-top": ""});
							}
						}
					});
				});
			});
	</script>
	<?php } ?>
	<?php echo $this->getChildHtml('ves_navigation'); ?>
</div>