<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-content" aria-label="block-customer-login-heading">
        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form-header"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <div class="login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="form-group control-icon required email">
					<input name="login[username]" placeholder="<?php echo __('Email') ?>" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email_header" type="email" class="input-text form-control" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                </div>
                <div class="form-group control-icon control-icon password required">
					<input placeholder="<?php echo __('Password') ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text form-control" id="pass_header" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                </div>
                <?php echo $block->getChildHtml('form_additional_info_login_header'); ?>
                <?php echo $block->getChildHtml('form_additional_info_login'); ?>
                <div class="actions-toolbar">
                    <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
					<div class="primary"><button type="submit" class="action login btn btn-custom" name="send" id="send2_header"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                </div>
            </div>
        </form>
    </div>
</div>
