<?php $_helper = $this->helper('MGS\Ajaxlayernavigation\Helper\Config');?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter mgs-filter" id="layered-filter-block">
        <div class="block-title filter-title">
            <strong><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">
			<h3 class="close-filter-fixed">
				<button id="close-filter"><i class="close-filter pe-7s-close pa"></i></button>
			</h3>
			<div class="block-filter-content">
				<?php echo $block->getChildHtml('state') ?>

				<?php //if ($block->getLayer()->getState()->getFilters()): ?>
				<?php if (false): ?>
					<div class="block-actions filter-actions">
						<a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
					</div>
				<?php endif; ?>
				<?php $wrapOptions = false; ?>
				<?php foreach ($block->getFilters() as $filter): ?>
						
						<?php if (!$wrapOptions): ?>
							<dl class="filter-options" id="narrow-by-list">
								<?php $wrapOptions = true; endif; ?>
								
								<?php 
									$isPrice = false;
									if($_helper->usePriceSlide()){ 
										$maxPrice = 0;
										$minPrice = 0;

										if ($filter->hasAttributeModel()) {
											$attributeModel = $filter->getAttributeModel();
											if ($attributeModel->getAttributeCode() == 'price') { 
												$isPrice = true;
												$minPrice = $filter->getMinPrice();
												$maxPrice = $filter->getMaxPrice();
											}
										}
									}		
								?>
								
								<?php if ($isPrice) : ?>
									<div class="filter-options-item ">
										<dt role="heading" aria-level="3">
											<div class="filter-options-title active"><?php echo __($_helper->getFilterByText(), $block->escapeHtml(__($filter->getName()))) ?></div></dt>
										<dd class="filter-options-content active">
										
											<div>
												<input type="text" id="price-range-slider" data-from="<?php echo $minPrice ?>" data-to="<?php echo $maxPrice ?>" name="price-range-slider" />
											</div>
										
										</dd>
									</div>
								<?php else : ?>
									<?php if ($filter->getItemsCount()): ?>
										<?php
											if ($filter->getFilterItemsCount()) {
												$itemIds = $filter->getFilterItemsCount();
												$attributteId = $filter->getAttributeModel()->getAttributeId();
												$itemProductIds[$attributteId] = $itemIds[$attributteId];
											}
											
										?>
										<div class="filter-options-item  filter-item">
											<dt role="heading" aria-level="3">
												<div class="filter-options-title active "><?php echo __($_helper->getFilterByText(), $block->escapeHtml(__($filter->getName()))) ?></div></dt>
											<dd class="filter-options-content active"> 
												<?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?>
											</dd>
										</div>
									<?php endif; ?>
								<?php endif; ?>
								
					<?php endforeach; ?>
							<?php if ($wrapOptions): ?>
							</div>
							<?php endif; ?>
				 
			</div>
        </div>
    </div>
	
	<script type="text/javascript">
		require([
			'jquery'
		], function ($) {
			$(document).ready(function(){
				$(document).on("click","#close-filter",function(e){
					$('body').removeClass('filter-active');	
				}); 
			}); 
		});
	</script>
<?php endif; ?>
