<?php 
$ves = $this->helper('Ves\Themesettings\Helper\Theme');
$show_sharelinks = $ves->getProductPageCfg('element_settings/show_sharelinks');
$show_sharelinks = false;
?>
<div class="goodsPop goodsShare goodsShare_pipelineGB loaded" id="js-popShare" style="display:none">
    <div class="goodsPop_cont goodsShare_cont">
        <?php if($show_sharelinks){ ?>
            <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
            <div class="mobile-share goodsShare_bar addthis_inline_share_toolbox_dym4">
                    <!-- AddThis Button BEGIN -->
                    <div class="addthis_toolbox addthis_default_style ">
                        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                        <a class="addthis_button_tweet"></a>
                        <a class="addthis_button_pinterest_pinit" pi:pinit:layout="horizontal"></a>
                        <a class="addthis_counter addthis_pill_style"></a>
                    </div>
                    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-538d2d303ab3eaa0"></script>
                    <!-- AddThis Button END -->
                    <div style="clear:both"></div>
            </div>
        <?php } ?>
        <a href="javascript:;" class="goodsShare_close js-close"><?php echo __("cancel");?></a>
    </div>
</div>