<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
	$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
	$canUsePanel = $themeHelper->acceptToUsePanel();
?>

<!-- Static block contact_page_custom_block -->
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_page_custom_block')->setCanUsePanel($canUsePanel)->toHtml(); ?>

<div class="contact-form-content">
    <div class="content-heading">
        <h3 class="title"><span><?php echo __('Get In Touch'); ?></span></h3>
    </div>
    <form class="form contact" action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>" id="contact-form" method="post" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
        <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="form-group name required">
                    <label for="name"><?php echo __('Name'); ?></label>
                    <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text form-control" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="form-group email required">
                    <label for="email"><?php echo __('Email'); ?></label>
                    <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="form-group telephone">
                    <label for="telephone"><?php echo __('Phone'); ?></label>
                    <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone') ?>" value="" class="input-text form-control" type="text" />
                </div>
            </div>
            <div class="col-xs-12">
                <div class="form-group comment required">
                    <label for="comment"><?php echo __('Content'); ?></label>
                    <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Content') ?>" class="input-text form-control" cols="5" rows="7" data-validate="{required:true}"></textarea>
                </div>
            </div>
        </div>
        <div class="actions-toolbar text-center margin-top35">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send') ?>" class="action submit btn btn-primary btn-lg">
                <span><?php /* @escapeNotVerified */ echo __('Send') ?></span>
            </button>
        </div>
    </form>
</div>
<?php echo $this->getLayout()->createBlock("Magento\Contact\Block\ContactForm")->setTemplate("Magento_Contact::map.phtml")->toHtml();?>