<?php
$collection = $this->getCollection();
$helper = $this->helper("Ves\Blog\Helper\Data");
$imageHelper = $this->helper("Ves\Blog\Helper\Image");


/** General Settings * */
$dateFormat = $helper->getConfig("general_settings/dateformat");
$twitterUsername = $helper->getConfig("general_settings/twitter_username");
$enableNetworks = $helper->getConfig("general_settings/enable_networks");
$networks = array_flip(explode(",", $helper->getConfig("general_settings/networks")));
$addthis_pubid     = $helper->getConfig("general_settings/addthis_pubid");
$addthis_pubid      = $addthis_pubid?$addthis_pubid:'ra-56ceab198f4f2e81';
$widget_title = $this->getConfig("widget_title");
$addition_class = $this->getConfig("addition_class");
$layout_type = $this->getConfig("layout_type");

$show_socialnetwork = $this->getConfig("show_socialnetwork");

/** JS setting * */
$filter_type = $this->getConfig("filter_type");

/** Post Settings * */
$show_image = $this->getConfig("show_image");
$image_width = (int) $this->getConfig("image_width", 800);
$image_height = (int) $this->getConfig("image_height");
$show_title = $this->getConfig("show_title");
$show_shortdescription = $this->getConfig("show_shortdescription");
$shortdescription_count = $this->getConfig("shortdescription_count");
$show_readmorelink = $this->getConfig("show_readmorelink");
$show_categories = $this->getConfig("show_categories");
$show_author = $this->getConfig("show_author");
$show_commentcount = $this->getConfig("show_commentcount");
$disable_comment = $helper->getConfig('general_settings/disable_comment');
if ($disable_comment) {
    $show_commentcount = false;
}
$show_updatedtime = $this->getConfig("show_updatedtime");
$show_createdtime = $this->getConfig("show_createdtime");
$show_hits = $this->getConfig("show_hits");
$show_tags = $this->getConfig("show_tags");

$html = '';

$cmsblock = $this->getConfig('cmsblock');
$pretext_html = $this->getConfig('pretext_html');
if ($cmsblock === 'pretext_html' && $pretext_html) {
    $html = base64_decode($pretext_html);
} elseif ($cmsblock != '') {
    $html = $this->getCmsBlockModel()->load($cmsblock)->getContent();
}
$html = $helper->filter($html);

$i = 1;
$x = 0;
$total = $collection->count();


$_postCollection = [];
$i = $x = 0;
foreach ($collection as $_post) {
    $i = 1;
    $x++;
    $_postCollection[$i][$x] = $_post;
}

$blockId = 'block' . time() . rand();

$classes = 'plist';
$list_category = [];
$list_tag = [];
$list_auth = [];
?>
<div class="block blog-posts latestposts-filter <?php echo $addition_class ?>">
    <?php if ($widget_title != '') { ?>
        <div class="block-title">
            <h2><?php echo $widget_title; ?></h2>
        </div>
    <?php } ?>
    <?php if ($html != '') { ?>
        <div class="pretext-html"><?php echo $html ?></div>
    <?php } ?>
    <!--===============================. Filter button .========================-->
    <?php
    if ($filter_type != '') {
        $filter_type = explode(",", $filter_type);
        foreach ($_postCollection as $_columnCollection) {
            foreach ($_columnCollection as $k => $_post) {
                if (in_array("categories", $filter_type)) {
                    $categories = $_post->getData('categories');
                    foreach ($categories as $v) {
                        if (!in_array($v['name'], $list_category)) {
                            $list_category[] = $v['name'];
                        }
                    }
                }
                if (in_array("tags", $filter_type)) {
                    $tags = $_post->getTag();
                    foreach ($tags as $k => $v) {
                        if (!in_array(trim($v['name']), $list_tag) && $v['name'] != "") {
                            $list_tag[] = trim($v['name']);
                        }
                    }
                }
                if (in_array("authors", $filter_type)) {
                    $author = $helper->getPostAuthor($_post);
                    if ($author && !in_array($author->getNickName(), $list_auth)) {
                        $list_auth[] = $author->getNickName();
                    }
                }
            }
        }
    }
    ?>
    <div class="filters">
        <?php if (count($list_category) > 0) { ?>
            <div class="filter_categories ui-group">
                <p class="ui-group__title"><strong><?php echo __('Categories')?></strong></p>
                <div class="button-group js-radio-button-group" data-filter-group="category">
                    <button class="button is-selected" data-filter=""><?php echo __('Any')?></button>
                    <?php foreach ($list_category as $v) { ?>
                        <button class="button" data-filter=".<?php echo str_replace(" ", "_", $v); ?>"><?php echo $v; ?></button>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
        <?php if (count($list_tag) > 0) { ?>
            <div class="filter_tags ui-group">
                <p class="ui-group__title"><strong><?php echo __('Tags')?></strong></p>
                <div class="button-group js-radio-button-group" data-filter-group="tags">
                    <button class="button is-selected" data-filter=""><?php echo __('Any')?></button>
                    <?php foreach ($list_tag as $v) { ?>
                        <button class="button" data-filter=".<?php echo str_replace(" ", "_", $v); ?>"><?php echo $v; ?></button>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>

        <?php if (count($list_auth) > 0) { ?>
            <div class="filter_authors ui-group">
                <p class="ui-group__title"><strong><?php echo __('Author')?></strong></p>
                <div class="button-group js-radio-button-group" data-filter-group="author">
                    <button class="button is-selected" data-filter=""><?php echo __('Any')?></button>
                    <?php foreach ($list_auth as $v) { ?>
                        <button class="button" data-filter=".<?php echo str_replace(" ", "_", $v); ?>"><?php echo $v; ?></button>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
    <!--===============================. END Filter button .========================-->
    <div class="block-content">
        <?php if ($total > 0) { ?>
            <ul id="<?php echo $blockId ?>" class="<?php echo $classes ?>" <?php // echo $carousel;?>>
                <?php
                foreach ($_postCollection as $_columnCollection) {
                    ?>
                    <li class="ves-post post-item">

                        <?php foreach ($_columnCollection as $_post) { ?>
                            <?php $postUrl = $helper->getPostUrl($_post); ?>
                            <?php $postLinkAttr = $helper->getPostUrlLinkAttr($_post); ?>
                            <?php
                            /* ===============================. Add class filter .============================ */
                            $class = '';
                            $categories = $_post->getData('categories');
                            foreach ($categories as $k => $v) {
                                $v['name'] = trim($v['name']);
                                $class .= str_replace(" ", "_", $v['name']) . " ";
                            }
                            $tags = $_post->getTag();
                            foreach ($tags as $k => $v) {
                                $v['name'] = trim($v['name']);
                                $class .= str_replace(" ", "_", $v['name']) . " ";
                            }
                            $author = $helper->getPostAuthor($_post);
                            if($author) {
                                $class .= str_replace(" ", "_", $author->getNickName());
                            }
                            /* ===============================. END Add class filter .======================== */
                            ?>
                            <div class="post-block <?php echo $class; ?>">
                                <?php if ($show_image) { ?>
                                    <div class="post-image">
                                        <a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>">
                                            <?php if ($_post->getThumbnailType() == 1 && $_post->getPostThumbnail() != '') { ?>
                                                <img src="<?php echo $imageHelper->resizeImage($_post->getPostThumbnail(), $image_width, $image_height) ?>" alt="<?php echo $_post->getTitle(); ?>"/>
                                            <?php } else if ($_post->getThumbnailType() == 2) { ?>
                                                <?php if ($_post->getThumbnailVideoType() == 1 && $_post->getThumbnailVideoId() != '') { ?>
                                                    <iframe width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" src="https://www.youtube.com/embed/<?php echo $_post->getThumbnailVideoId() ?>" frameborder="0" allowfullscreen></iframe>
                                                <?php } else if ($_post->getThumbnailVideoType() == 2 && $_post->getThumbnailVideoId() != '') { ?>
                                                    <iframe src="https://player.vimeo.com/video/<?php echo $_post->getThumbnailVideoId() ?>?color=3498DB&title=0&byline=0&portrait=0" width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                                                <?php } ?>
                                            <?php } ?>
                                        </a>
                                    </div>
                                <?php } ?>
                                <div class="post-meta">
                                    <?php if ($show_title) { ?>
                                        <div class="post-title">
                                            <h4><a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>"><?php echo $_post->getTitle(); ?></a></h4>
                                        </div>
                                    <?php } ?>
                                    <?php if ($show_author) { ?>
                                        <div class="post-author">
                                            <?php $author = $helper->getPostAuthor($_post); ?>
                                            <i class="fa fa-user"></i> <a href="<?php echo $helper->getAuthorUrl($author); ?>" title="<?php echo $author->getNickName() ?>"><?php echo $author->getNickName() ?></a>
                                        </div>
                                    <?php } ?>
                                    <?php if ($show_createdtime || $show_updatedtime) { ?>
                                        <div class="post-date">
                                            <?php if ($show_createdtime) { ?>
                                                <?php $createdTime = $helper->getFormatDate($_post->getCreationTime(), $dateFormat); ?>
                                                <span><?php echo __('Created on %1', $createdTime); ?></span>
                                            <?php } ?>
                                            <?php if ($show_updatedtime) { ?>
                                                <?php $updateTime = $helper->getFormatDate($_post->getUpdateTime(), $dateFormat); ?>
                                                <span><?php echo __('Updated on %1', $updateTime); ?></span>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                    <?php if ($show_commentcount) { ?>
                                        <div class="post-comment">
                                            <?php echo __('%1 comments', $_post->getCommentCount()); ?>
                                        </div>
                                    <?php } ?>
                                    <?php if ($show_categories) { ?>
                                        <div class="post-categories">
                                            <?php echo __('Pubslished In: ') ?>
                                            <?php
                                            $categories = $_post->getData('categories');
                                            $count = count($categories);
                                            ?>
                                            <?php foreach ($categories as $k => $v) { ?>
                                                <a href="<?php echo $helper->getCategoryUrl($v['identifier']) ?>" title="<?php echo $v['name'] ?>"><?php echo $v['name'] ?></a>
                                                <?php if (isset($categories[$k + 1])) echo __(', '); ?>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                    <?php if ($show_hits) { ?>
                                        <div class="post-hits"><span><?php echo __("Read"); ?></span> <strong><?php echo (int) $_post->getHits(); ?></strong> <?php echo __("Times"); ?></div>
                                    <?php } ?>
                                    <?php if ($show_socialnetwork) { ?>
                                        <div class="post-social">
                                            <!-- Go to www.addthis.com/dashboard to customize your tools -->
                                            <div class="addthis_toolbox addthis_default_style addthis_16x16_style">
                                                <a class="addthis_button_facebook"></a>
                                                <a class="addthis_button_twitter"></a>
                                                <a class="addthis_button_google"></a>
                                                <a class="addthis_button_email"></a>
                                                <a class="addthis_button_pinterest_share"></a>
                                                <a class="addthis_button_compact"></a>
                                            </div>
                                        </div>
                                    <?php } ?>
                                    <?php if ($show_tags) { ?>
                                        <?php $tags = $_post->getTag(); ?>
                                        <?php if (!empty($tags)) { ?>
                                            <div class="post-tag">
                                                <span><?php echo __('Tags:'); ?></span>
                                                <?php foreach ($tags as $k => $v) { ?>
                                                    <a href="<?php echo $helper->getTagUrl($v['alias']) ?>"><?php echo $v['name'] ?></a>
                                                    <?php if (isset($tags[$k + 1])) echo __(', '); ?>
                                                <?php } ?>
                                            </div>
                                        <?php } ?>
                                    <?php } ?>
                                    <?php if ($show_shortdescription) { ?>
                                        <div class="post-readmore">
                                            <?php $shortContent = $_post->getShortContent(); ?>
                                            <?php echo $helper->subString($shortContent, (int) $shortdescription_count); ?>
                                            <?php if ($show_readmorelink) { ?>
                                                <br><a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>"><?php echo __('Read more') ?></a>
                                            <?php } ?>	
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        <?php } ?>

                    </li>
                <?php } ?>
            </ul>
        <?php } ?>
        <?php if ($show_socialnetwork) { ?>
            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $addthis_pubid; ?>"></script>
        <?php } ?>
    </div>
</div>
<?php if ($filter_type) { ?>
    <script>
        requirejs(['require', 'jquery', 'jquery.Isotope'],
            function (require, $, Isotope) {
                require(['jquery.Bridget'],
                    function (jQueryBridget) {
                        jQueryBridget('isotope', Isotope, $);
                        var grid = $('.block-content ul li').isotope({
                            itemSelector: '.post-block'
                        });
                        var filters = {};

                        $('.filters').on('click', '.button', function () {
                            var $this = $(this);
                            var $buttonGroup = $this.parents('.button-group');
                            var filterGroup = $buttonGroup.attr('data-filter-group');
                            filters[ filterGroup ] = $this.attr('data-filter');
                            var filterValue = concatValues(filters);
                            grid.isotope({filter: filterValue});
                        });

                        $('.button-group').each(function (i, buttonGroup) {
                            var $buttonGroup = $(buttonGroup);
                            $buttonGroup.on('click', 'button', function () {
                                $buttonGroup.find('.is-selected').removeClass('is-selected');
                                $(this).addClass('is-selected');
                            });
                        });
                        function concatValues(obj) {
                            var value = '';
                            for (var prop in obj) {
                                value += obj[ prop ];
                            }
                            return value;
                        }

                });
        });
    </script>

<?php } ?>