<?php
$collection  = $this->getCollection();
$helper      = $this->helper("Ves\Blog\Helper\Data");
$imageHelper = $this->helper("Ves\Blog\Helper\Image");


/** General Settings **/
$dateFormat      = $helper->getConfig("general_settings/dateformat");
$twitterUsername = $helper->getConfig("general_settings/twitter_username");
$enableNetworks  = $helper->getConfig("general_settings/enable_networks");
$networks        = array_flip(explode(",", $helper->getConfig("general_settings/networks")));
$widget_title    = $this->getConfig("widget_title");
$addition_class  = $this->getConfig("addition_class");
$layout_type     = $this->getConfig("layout_type");
$widgetStyle     = $this->getConfig('widget_style');
$titleColor      = $this->getConfig('title_color');

/** Post Settings **/
$show_image             = $this->getConfig("show_image");
$image_width            = (int)$this->getConfig("image_width", 800);
$image_height           = (int)$this->getConfig("image_height");
$show_title             = $this->getConfig("show_title");
$show_shortdescription  = $this->getConfig("show_shortdescription");
$shortdescription_count = $this->getConfig("shortdescription_count");
$show_readmorelink      = $this->getConfig("show_readmorelink");
$readmoreBgColor		= $this->getConfig("rebg_color");
$readmoreColor			= $this->getConfig("re_color");
$readmoreStyle = '';
if($readmoreBgColor) $readmoreStyle .= 'background: ' . $readmoreBgColor . ';';
if($readmoreColor) $readmoreStyle .= 'color: ' . $readmoreColor . ';';
if($readmoreStyle!='') $readmoreStyle = 'style="' . $readmoreStyle .'"';
$show_categories        = $this->getConfig("show_categories");
$show_author            = $this->getConfig("show_author");
$show_commentcount      = $this->getConfig("show_commentcount");
$disable_comment 		= $helper->getConfig('general_settings/disable_comment');
if($disable_comment) {
	$show_commentcount = false;
}
$show_updatedtime       = $this->getConfig("show_updatedtime");
$show_createdtime       = $this->getConfig("show_createdtime");
$show_hits              = $this->getConfig("show_hits");
$show_tags              = $this->getConfig("show_tags");
$show_socialnetworks    = $this->getConfig("show_socialnetwork");
$item_height            = (int)$this->getConfig("item_height");


/** Owl Carousel Settings **/
$item_height           = (int)$this->getConfig("item_height");
$number_item_percolumn = $this->getConfig("number_item_percolumn");
$large_max_items       = $this->getConfig("large_max_items");
$large_items           = $this->getConfig("large_items");
$portrait_items        = $this->getConfig("portrait_items");
$tablet_items          = $this->getConfig("tablet_items");
$tablet_small_items    = $this->getConfig("tablet_small_items");
$mobile_items          = $this->getConfig("mobile_items");
$rtl                   = $this->getConfig("rtl");
$autoplay              = $this->getConfig("autoplay");
$autoplay_timeout      = $this->getConfig("autoplay_timeout");
$autoplay_hoverpause   = $this->getConfig("autoplay_hoverpause");
$dots                  = $this->getConfig("dots");
$nav                   = $this->getConfig("nav");
$nav_prev              = str_replace("'", '"', $this->getConfig("nav_prev"));
$nav_next              = str_replace("'", '"', $this->getConfig("nav_next"));
$loop                  = $this->getConfig("loop");
$mousedrag             = $this->getConfig("mousedrag");
$touchdrag             = $this->getConfig("touchdrag");
$pulldrag              = $this->getConfig("pulldrag");

$html = '';

$cmsblock = $this->getConfig('cmsblock');
$pretext_html = $this->getConfig('pretext_html');
if($cmsblock === 'pretext_html' && $pretext_html){
	$html = base64_decode($pretext_html);
}elseif($cmsblock!=''){
	$html = $this->getCmsBlockModel()->load($cmsblock)->getContent();
}
$html = $helper->filter($html);

$i = 1;
$x = 0;
$total = $collection->count();

if($total%$number_item_percolumn == 0){
	$column = $total/$number_item_percolumn;
}else{
	$column = floor($total/$number_item_percolumn)+1;
}

$_postCollection = [];
$i = $x = 0;
foreach ($collection as $_post) {
	if($i<$column){
		$i++;
	}else{
		$i = 1;
		$x++;
	}
	$_postCollection[$i][$x] = $_post;
}

$blockId = 'block' . time().rand();
$classes = '';
$carousel = '';
if($layout_type == 'owl_carousel'){
	$classes = 'owl-carousel owl-theme';
	$carousel .= 'data-items="'.$this->getConfig("column", 3).'"';
	$carousel .= 'data-mousedrag="';
		$carousel .= $this->getConfig("mousedrag")?"true":"false";
	$carousel .= '"';
	$carousel .= 'data-pulldrag="';
		$carousel .= $this->getConfig("pulldrag")?"true":"false";
	$carousel .='"';
	$carousel .= 'data-freedrag="';
		$carousel .= $this->getConfig("freedrag")?"true":"false";
	$carousel .='"';
	$carousel .= 'data-stagepadding="';
		$carousel .= (int)$this->getConfig("stagepadding");
	$carousel .= '"';
	$carousel .= 'data-lazyload="';
		$carousel .= $this->getConfig("lazyload")?"true":"false";
	$carousel .= '"';
	$carousel .= 'data-rtl="';
		$carousel .= $this->getConfig("rtl")?"true":"false";
	$carousel .= '"';
	$carousel .= 'data-center="';
		$carousel .= $this->getConfig("center")?"true":"false";
	$carousel .='"';
	$carousel .= 'data-margin="';
		$carousel .= (int)$this->getConfig("margin");
	$carousel .='"';
	$carousel .= 'data-autoplay="';
		$carousel .= $this->getConfig("autoplay")?"true":"false";
	$carousel .= '"';
	$carousel .= 'data-autoplay-timeout="';
		$carousel .= $this->getConfig("autoplay_timeout", 3000);
	$carousel .= '"';
	$carousel .= 'data-dots="';
		$carousel .= $this->getConfig("dots")?"true":"false";
	$carousel .= '"';
	$carousel .= 'data-loop="';
		$carousel .= $this->getConfig("loop")?"true":"false";
	$carousel .= '"';
	$carousel .= 'data-nav = "';
		$carousel .= $this->getConfig("nav")?"true":"false";
	$carousel .= '"';
	if($nav_prev){
		$carousel .='data-nav-text-owlpre="' . str_replace('"', "'", $nav_prev) . '"';
	}
	if($nav_next){
    	$carousel .='data-nav-text-owlnext="' . str_replace('"', "'", $nav_next) . '"';
	}
	$carousel .= 'data-autoplay-pauonhover="';
	$carousel .= $this->getConfig("autoplay_hoverpause")?"true":"false";
	$carousel .= '"';
	$carousel .= 'data-mobile-items="'.$mobile_items.'"';
	$carousel .= 'data-tablet-small-items="'.$tablet_small_items.'"';
	$carousel .= 'data-tablet-items="'.$tablet_small_items.'"';
	$carousel .= 'data-portrait-items="'.$portrait_items.'"';
	$carousel .= 'data-large-items="'.$large_items.'"';
	$carousel .= 'data-large-max-items="'.$large_max_items.'"';
}else{
	$classes = 'plist';
}

?>
<div class="block ves-blog post-list postsstyle-style4 postsgrid1 blog-widget blog-widget-<?php echo $widgetStyle ?>">
	<?php if($widget_title!=''){ ?>
	<div class="block-title">
		<h2 <?php if($titleColor!=''){ echo 'style="color: ' . $titleColor . '"'; } ?>><strong><?php echo $widget_title; ?></strong></h2>
	</div>
	<?php } ?>
	<?php if($html!=''){ ?>
	<div class="pretext-html"><?php echo $html ?></div>
	<?php } ?>
	<div class="block-content blog-grid" <?php if($border_color = $this->getConfig('border_color')){ echo 'style="border-bottom-color: ' . $border_color . '"'; } ?>>
		<?php if($total>0){ ?>
		<ul id="<?php echo $blockId ?>" class="<?php echo $classes ?> ves-timeline-ulist" <?php echo $carousel; ?>>
			<?php $c=0; foreach ($_postCollection as $_columnCollection) { $c++; ?>
			<li class="ves-post ves-timeline-list-item">
				<?php
				$y = 0;
				?>
				<?php foreach ($_columnCollection as $_post){ ?>
				<?php $postUrl = $helper->getPostUrl($_post); ?>
				<?php $postLinkAttr = $helper->getPostUrlLinkAttr($_post); ?>
				<?php
				$style = '';
				if($layout_type=='owl_carousel' && $item_height>0){
					$style = 'style="height:' . $item_height . 'px"';
				}
				?>
				<?php if($c%2 == 1) { $a = 1; $b=2; ?>
				<div class="ves-timeline-col<?php echo $a; ?>">
					<?php if($show_createdtime || $show_updatedtime){ ?>
					<div class="post-date">
						<?php if($show_createdtime){ ?>
						<?php $createdTime = $helper->getFormatDate($_post->getCreationTime(), $dateFormat); ?>
						<i class="fa fa-clock-o"></i> <span><?php echo $createdTime; ?></span>
						<?php } ?>
						<?php if($show_updatedtime){ ?>
						<?php $updateTime = $helper->getFormatDate($_post->getUpdateTime(), $dateFormat); ?>
						<i class="fa fa-clock-o"></i> <span><?php echo __('Updated on %1', $updateTime); ?></span>
						<?php } ?>
					</div>
					<?php } ?>
				</div>
				<?php }else { $b=1; } ?>
				<div class="ves-timeline-col<?php echo $b; ?>">
					<div class="ves-post post-item other-items" <?php echo $style; ?>>
						<div class="post-wrapper">
							<?php if($show_image){ ?>
							<?php $imageClass = ''; ?>
							<?php if($_post->getImageType() == 2 && $_post->getImageVideoId()!=''){
								$imageClass = ' post-video';
							} ?>
							<div class="post-image <?php echo $imageClass; ?>">
								<a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>">
									<?php if( $_post->getThumbnailType() == 1 && $_post->getPostThumbnail()!=''){ ?>
									<?php if($_post->getImageType() == 2 && $_post->getImageVideoId()!=''){ ?>
									<span class="fa overlay-icon"></span>
									<?php }else{ ?>
									<span class="fa overlay-icon"></span>
									<?php } ?>
									<?php if($image_width>0){ ?>
									<img src="<?php echo $imageHelper->resizeImage($_post->getPostThumbnail(), $image_width, $image_height) ?>" height="<?php echo $image_height ?>" width="<?php echo $image_width ?>" alt="<?php echo $_post->getTitle(); ?>"/>
									<?php }else{ ?>
									<img src="<?php echo $helper->getMediaUrl($_post->getThumbnail()) ?>" alt="<?php echo $_post->getTitle(); ?>"/>
									<?php } ?>
									<?php }else if($_post->getThumbnailType() == 2){ ?>
									<?php if($_post->getThumbnailVideoType()==1 && $_post->getThumbnailVideoId()!=''){ ?>
									<iframe width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" src="https://www.youtube.com/embed/<?php echo $_post->getThumbnailVideoId() ?>" frameborder="0" allowfullscreen></iframe>
									<?php }else if($_post->getThumbnailVideoType()==2 && $_post->getThumbnailVideoId()!=''){ ?>
									<iframe src="https://player.vimeo.com/video/<?php echo $_post->getThumbnailVideoId() ?>?color=3498DB&title=0&byline=0&portrait=0" width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
									<?php } ?>
									<?php } ?>
								</a>
							</div>
							<?php } ?>

							<?php if($show_title){ ?>
							<h2 class="post-title"><a <?php if($titleColor){ ?>data-hover-color="<?php echo $titleColor ?>"<?php } ?> href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>"><?php echo $_post->getTitle(); ?></a></h2>
							<?php } ?>
							<?php if($show_socialnetworks){ ?>
							<div class="post-socials">
								<div class="addthis_toolbox addthis_default_style" data-title="<?php echo $_post->getTitle(); ?>" addthis:url="<?php echo $postUrl ?>">
									<a class="addthis_button_facebook"></a>
									<a class="addthis_button_twitter"></a>
									<a class="addthis_button_google"></a>
									<a class="addthis_button_email"></a>
									<a class="addthis_button_pinterest_share"></a>
									<a class="addthis_button_compact"></a>
								</div>
							</div>
							<?php } ?>
							<div class="post-meta">
								<?php if($show_author){ ?>
								<div class="post-author">
									<?php $author = $helper->getPostAuthor($_post);?>
									<i class="fa fa-user"></i> <a href="<?php echo $helper->getAuthorUrl($author); ?>" title="<?php echo $author->getNickName() ?>"><?php echo $author->getNickName() ?></a>
								</div>
								<?php } ?>
								
								<?php if($show_categories){ ?>
								<div class="post-categories">
									<?php
									$categories = $_post->getData('categories');
									$count = count($categories);
									?>
									<i class="fa fa-folder"></i> 
									<?php foreach ($categories as $k => $v) { ?>
									<a href="<?php echo $helper->getCategoryUrl($v['identifier'])  ?>" title="<?php echo $v['name'] ?>"><?php echo $v['name'] ?></a>
									<?php if(isset($categories[$k+1])) echo __(', '); ?>
									<?php } ?>
								</div>
								<?php } ?>
								<?php if($show_hits){ ?>
								<div class="post-hits"><i class="fa fa-eye"></i> <span><?php echo (int)$_post->getHits(); ?></span></div>
								<?php } ?>
								<?php if($show_commentcount){ ?>
								<div class="post-comment">
									<i class="fa fa-comments"></i> <a href="<?php echo $postUrl ?>#comments" <?php echo $postLinkAttr;?>><?php echo $_post->getCommentCount(); ?></a>
								</div>

								<?php } ?>
							</div>
							<?php if($show_tags){ ?>
							<?php $tags = $_post->getTag(); ?>
							<?php if(!empty($tags)){ ?>
							<div class="post-tag">
								<span><?php echo __('Tags:'); ?></span>
								<?php foreach ($tags as $k => $v) { ?>
								<a href="<?php echo $helper->getTagUrl($v['alias']) ?>"><?php echo trim($v['name']) ?></a>
								<?php if(isset($tags[$k+1])) echo __(', '); ?>
								<?php } ?>
							</div>
							<?php } ?>
							<?php } ?>
							<?php if($show_shortdescription){ ?>
							<div class="post-summary">
								<?php $shortContent = $_post->getShortContent(); ?>
								<?php echo $helper->subString($shortContent, (int)$shortdescription_count); ?>
							</div>
							<?php if($show_readmorelink){ ?>
							<div class="post-readmore"><a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>" <?php echo $readmoreStyle ?>><?php echo __('Read more') ?> <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
							<?php } ?>
							<?php } ?>
						</div>
					</div>
				</div>
				<?php if($c%2 == 0) { $a = 2;  ?>
				<div class="ves-timeline-col<?php echo $a; ?>">
					<?php if($show_createdtime || $show_updatedtime){ ?>
					<div class="post-date">
						<?php if($show_createdtime){ ?>
						<?php $createdTime = $helper->getFormatDate($_post->getCreationTime(), $dateFormat); ?>
						<i class="fa fa-clock-o"></i> <span><?php echo $createdTime; ?></span>
						<?php } ?>
						<?php if($show_updatedtime){ ?>
						<?php $updateTime = $helper->getFormatDate($_post->getUpdateTime(), $dateFormat); ?>
						<i class="fa fa-clock-o"></i> <span><?php echo __('Updated on %1', $updateTime); ?></span>
						<?php } ?>
					</div>
					<?php } ?>
				</div>
				<?php } ?>	
				<?php $y++; ?>
				<?php } ?>
			</li>
			<?php } ?>
		</ul>
		<?php } ?>
		<?php if($layout_type =='owl_carousel'){ ?>
		<script>
			require([
				'jquery'
				], function($){
					jQuery(document).ready(function() {

						var anchorColor = '';
						$('#<?php echo $blockId ?> a').hover(function(){
							anchorColor = '';
							if($(this).data('hover-color')!=''){
								$(this).css('color',$(this).data('hover-color'));
							}
						}, function(){
							$(this).css('color','');
						})

						
					});
				});
			</script>
			<?php } ?>

			<?php if($show_socialnetworks){ ?>
			<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-56ceab198f4f2e81"></script>
			<?php } ?>
		</div>
	</div>