<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$size = $themeHelper->getImageSizeForDetails();
$ratio = $size['width']/$size['height'];
$widthThumb = $block->getImageAttribute('product_page_image_small', 'width');
$heightThumb = $widthThumb/$ratio;
?>

<?php // Image 360 ?>
<?php $rotateImage = $_product->getData('mgs_j360') ?>
<?php $rotateImages = [] ?>
<?php if($rotateImage): ?>
	<?php $rotateImages = $themeHelper->getRotateImages($_product->getId()) ?>
<?php endif ?>
<?php if($rotateImage && (count($rotateImages)>0)): ?>
<a class="rotate-image" href="#" onclick="rotate360(); return false"></a>
<?php endif ?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
                "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson(); ?>,
                "options": {
                    "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                    "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/loop"); ?>,
                    "keyboard": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/keyboard"); ?>,
                    "arrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/arrows"); ?>,
                    "allowfullscreen": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/allowfullscreen"); ?>,
                    "showCaption": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/caption"); ?>,
                    "width": <?php /* @escapeNotVerified */ echo $size['width']; ?>,
                    "thumbwidth": <?php /* @escapeNotVerified */ echo $widthThumb; ?>,
                    "thumbheight": <?php /* @escapeNotVerified */ echo $heightThumb; ?>,
					"widthOffset": "200", 
					"heightOffset": <?php /* @escapeNotVerified */ echo $heightThumb; ?>,
                    "height": <?php /* @escapeNotVerified */ echo $size['height']; ?>,
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/duration"); ?>,
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/effect"); ?>",
                    "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/navarrows"); ?>,
                    "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navdir"); ?>"
                },
                "fullscreen": {
                    "nav": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/nav"); ?>",
                    "loop": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/loop"); ?>,
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                    "arrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                    "showCaption": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/caption"); ?>,
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                },
                "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>
            }
        }
    }
</script>


<?php if($rotateImage && (count($rotateImages)>0)): ?>
	<script type="text/javascript">
		function rotate360(){
			require([
				'jquery',
				"mage/translate",
				'rotateImage'
			], function ($) {
				$.ajax({
					url: '<?php echo $this->getUrl('mpanel/index/rotate') ?>',
					data: ('&product=<?php echo $_product->getId() ?>'),
					type: 'get',
					dataType: 'json',
					cache: true,
					showLoader: true
				}).done(function (response) {
					$('.loading-mask').append(response.html);
					$('.loading-mask').addClass('j360-container');
					setTimeout(initImageRotate, 1);
					
				}).fail(function (error) {
					alert($.mage.__('Sorry, something went wrong. Please try again later.'));
				});
			});
		}
		
		function initImageRotate(){
			require([
				'jquery',
				"mage/translate",
				'rotateImage'
			], function ($) {
				$('.loading-mask').show();
				$('#mgs_j360').j360();
			});
		}
		
		function closeRotateContainer(){
			require([
				'jquery',
				"mage/translate",
				'rotateImage'
			], function ($) {
				$('.rotate-image-container').remove();
				$('.loading-mask').removeClass('j360-container');
				$('.loading-mask').hide();
				$('.preload_img').parent().remove();
			});
		}
	</script>
<?php endif ?>