<?php
$collection  = $this->getCollection();
$helper      = $this->helper("Ves\Blog\Helper\Data");
$imageHelper = $this->helper("Ves\Blog\Helper\Image");
$category    = $this->getCategory();

/** General Settings **/
$maincontainer_selector     = $helper->getConfig("general_settings/maincontainer_selector");
$maincontainer_selector = $maincontainer_selector?$maincontainer_selector:'.column.main';
$dateFormat         = $helper->getConfig("general_settings/dateformat");
$twitterUsername    = $helper->getConfig("general_settings/twitter_username");
$enableNetworks     = $helper->getConfig("general_settings/enable_networks");
$networks           = array_flip(explode(",", $helper->getConfig("general_settings/networks")));
$layout             = $category->getLayoutType();
$show_toolbartop    = $helper->getConfig("category_page/show_toolbartop");
$show_toolbarbottom = $helper->getConfig("category_page/show_toolbarbottom");

$itemsperpage       = (int)$category->getItemPerPage();
$lg_column_item     = (int)$category->getLgColumnItem();
$md_column_item     = (int)$category->getMdColumnItem();
$sm_column_item     = (int)$category->getSmColumnItem();
$xs_column_item     = (int)$category->getXsColumnItem();
$lg_column          = 12/$lg_column_item;
$md_column          = 12/$md_column_item;
$sm_column          = 12/$sm_column_item;
$xs_column          = 12/$xs_column_item;

/** POST Settings **/
$show_image             = $this->getConfig("category_page/show_image");
$image_width            = (int)$this->getConfig("category_page/image_width", 800);
$image_height           = (int)$this->getConfig("category_page/image_height");
$show_title             = $this->getConfig("category_page/show_title");
$show_shortdescription  = $this->getConfig("category_page/show_shortdescription");
$shortdescription_count = $this->getConfig("category_page/shortdescription_count");
$show_readmorelink		= $this->getConfig("category_page/show_readmorelink");
$show_categories        = $this->getConfig("category_page/show_categories");
$show_author            = $this->getConfig("category_page/show_author");
$show_commentcount      = $this->getConfig("category_page/show_commentcount");
$disable_comment 		= $this->getConfig('general_settings/disable_comment');
if($disable_comment) {
	$show_commentcount = false;
}
$show_updatedtime       = $this->getConfig("category_page/show_updatedtime");
$show_createdtime       = $this->getConfig("category_page/show_createdtime");
$show_hits              = $this->getConfig("category_page/show_hits");
$show_image             = $this->getConfig("category_page/show_image");
$show_tags              = $this->getConfig("category_page/show_tags");
$blockId = 'blog-' . $layout . time();
?>

<?php if($collection->count()){ ?>
<?php $total = count($collection->getItems()); ?>
<div class="ves-blog">
	<?php if($show_toolbartop){ ?>
	<div class="blog-toolbar">
		<?php echo $block->getChildHtml('toolbar'); ?>
	</div>
	<?php } ?>
	<div class="blog-<?php echo $layout ?> blog-posts">
		<?php echo $this->getPostsBlock(); ?>
	</div>
	<?php if($show_toolbarbottom){ ?>
	<div class="blog-toolbar">
		<?php echo $block->getChildHtml('toolbar'); ?>
	</div>
	<?php } ?>
</div>
<?php if($layout=='masonry'){ ?>
<script>
	function initBlogMasonryLayout($, Masonry) {
		var width = $(window).width();
		var column = <?php echo $lg_column_item ?>;
		if(width<480){
			column = <?php echo $xs_column_item ?>;
			w = w - 20;
		}
		if(width>=480){
			column = <?php echo $sm_column_item ?>;
		}
		if(width>=992){
			column = <?php echo $md_column_item ?>;
		}
		if(width>=1200){
			column = <?php echo $lg_column_item ?>;
		}
		var w = $('<?php echo $maincontainer_selector ; ?>').width() + 20;
		$('.<?php echo $blockId; ?>').css({"width":w+"px"});
		var masoW = 100/column;
		$('.blog-masonry .post-item').css({"width":masoW+"%","margin-bottom":"20px"});
		new Masonry( '.blog-masonry', {
			itemSelector: '.post-item'
		});
		$('.blog-masonry').css('visibility', 'visible');
	}
		require([
			'jquery',
			'Ves_Blog/js/masonry.pkgd.min'
			], function($, Masonry){
				jQuery(document).ready(function($) {
					$(window).on("resize", function(){
						initBlogMasonryLayout($, Masonry);
					}).resize();
				});
			});
	</script>
	<?php } ?>

	<?php } ?>