<?php
$collection  = $this->getCollection();
$helper      = $this->helper("Ves\Blog\Helper\Data");
$imageHelper = $this->helper("Ves\Blog\Helper\Image");

/** General Settings **/
$dateFormat         = $helper->getConfig("general_settings/dateformat");
$twitterUsername    = $helper->getConfig("general_settings/twitter_username");
$enableNetworks     = $helper->getConfig("general_settings/enable_networks");
$layout             = $helper->getConfig("post_page/related_carousel_layout");
$networks           = array_flip(explode(",", $helper->getConfig("general_settings/networks")));
$default_items      = (int)$helper->getConfig('post_page/default_items');
$mobile_items       = (int)$helper->getConfig('post_page/mobile_items');
$tablet_small_items = (int)$helper->getConfig('post_page/tablet_small_items');
$tablet_items       = (int)$helper->getConfig('post_page/tablet_items');
$portrait_items     = (int)$helper->getConfig('post_page/portrait_items');
$large_items        = (int)$helper->getConfig('post_page/large_items');
$autoplay           = $helper->getConfig('post_page/autoplay');
$autoplay_timeout   = $helper->getConfig('post_page/autoplay_timeout');
$dots               = $helper->getConfig('post_page/dots');
$nav                = $helper->getConfig('post_page/nav');
$nav_prev           = $helper->getConfig('post_page/nav_prev');
$nav_next           = $helper->getConfig('post_page/nav_next');



/** POST Settings **/
$show_image                    = $this->getConfig("show_image");
$image_width                   = (int)$this->getConfig("image_width");
if(!$image_width) $image_width = 800;
$image_height                  = (int)$this->getConfig("image_height");
$show_title                    = $this->getConfig("show_title");
$show_shortdescription         = $this->getConfig("show_shortdescription");
$shortdescription_count        = $this->getConfig("shortdescription_count");
$show_readmorelink             = $this->getConfig("show_readmorelink");
$show_categories               = $this->getConfig("show_categories");
$show_author                   = $this->getConfig("show_author");
$show_commentcount             = $this->getConfig("show_commentcount");
$disable_comment 			   = $helper->getConfig('general_settings/disable_comment');
if($disable_comment) {
	$show_commentcount 		   = false;
}
$show_updatedtime              = $this->getConfig("show_updatedtime");
$show_createdtime              = $this->getConfig("show_createdtime");
$show_hits                     = $this->getConfig("show_hits");
$show_tags                     = $this->getConfig("show_tags");

$i = 1;
$x = 0;
$total = $collection->getSize();
$carousel = '';
if($layout == 'owl_carousel') {
	$carousel .= 'data-items="3" data-rtl="false" data-loop="false" data-nav="';
	$carousel .= $nav?'true':'false';
	$carousel .= '"';
	$carousel .= 'data-dots="';
	$carousel .= $dots?'true':'false';
	$carousel .= '" data-responsive-refresh-rate="false"';
	if($autoplay) {
		$carousel .= 'data-autoplay="true" data-autoplay-pauonhover="true" data-autoplay-timeout="';	
		$carousel .= $autoplay_timeout;
		$carousel .= '" ';
	}
	$carousel .= 'data-mobile-items="'.$mobile_items.'" ';
	$carousel .= 'data-tablet-small-items="'.$tablet_small_items.'" ';
	$carousel .= 'data-tablet-items="'.$tablet_items.'" ';
	$carousel .= 'data-portrait-items="'.$portrait_items.'" ';
	$carousel .= 'data-large-items="'.$large_items.'" ';
	$carousel .= 'data-large-max-items="'.$large_items.'" ';
	$carousel .= 'data-nav-text-owlpre="' . $nav_prev . '" ';
	$carousel .= 'data-nav-text-owlnext="' . $nav_next . '" ';
	$carousel .= 'data-margin="10" ';
}
?>
<?php if($total>0){ ?>
<div class="ves-block blog-posts post-list posts-related blog-widget">
	<div class="block-title">
		<h2><strong><?php echo __('Related Posts') ?></strong></h2>
	</div>
	<div class="block-content">
		<ul class="<?php if($layout == 'owl_carousel'){ ?>post-owl owl-carousel post-listing" <?php echo $carousel; } ?>>
			<?php foreach ($collection as $_post) {  ?>
			<?php  
			$postUrl = $helper->getPostUrl($_post);
			$postLinkAttr = $helper->getPostUrlLinkAttr($_post);
			?>

			<li class="ves-post post-item">
				<?php if($show_image){ ?>
				<?php $imageClass = ''; ?>
				<?php if($_post->getImageType() == 2 && $_post->getImageVideoId()!=''){
					$imageClass = ' post-video';
				} ?>
			<div class="post-image <?php echo $imageClass; ?>">
				<a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr; ?> title="<?php echo $_post->getTitle(); ?>">
					<?php if( $_post->getThumbnailType() == 1 && $_post->getPostThumbnail()!=''){ ?>
						<?php if($_post->getImageType() == 2 && $_post->getImageVideoId()!=''){ ?>
						<span class="fa overlay-icon"></span>
					<?php }else{ ?>
						<span class="fa overlay-icon"></span>
					<?php } ?>
					<?php if($image_width>0){ ?>
					<img src="<?php echo $imageHelper->resizeImage($_post->getPostThumbnail(), $image_width, $image_height) ?>" height="<?php echo $image_height ?>" width="<?php echo $image_width ?>" alt="<?php echo $_post->getTitle(); ?>"/>
					<?php }else{ ?>
					<img src="<?php echo $helper->getMediaUrl($_post->getPostThumbnail()) ?>" alt="<?php echo $_post->getTitle(); ?>"/>
					<?php } ?>
					<?php }else if($_post->getThumbnailType() == 2){ ?>
					<?php if($_post->getThumbnailVideoType()==1 && $_post->getThumbnailVideoId()!=''){ ?>
					<iframe width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" src="https://www.youtube.com/embed/<?php echo $_post->getThumbnailVideoId() ?>" frameborder="0" allowfullscreen></iframe>
					<?php }else if($_post->getThumbnailVideoType()==2 && $_post->getThumbnailVideoId()!=''){ ?>
					<iframe src="https://player.vimeo.com/video/<?php echo $_post->getThumbnailVideoId() ?>?color=3498DB&title=0&byline=0&portrait=0" width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
					<?php } ?>
					<?php } ?>
				</a>

			</div>
			<?php } ?>
				<div class="post-meta">
					<?php if($show_title){ ?>
					<div class="post-title">
						<?php if($layout == 'list'){ ?>
						<a href="<?php echo $postUrl ?>"  <?php echo $postLinkAttr; ?> title="<?php echo $_post->getTitle(); ?>"><?php echo $i .') ' . $_post->getTitle(); ?></a>
						<?php }else{ ?>
						<a href="<?php echo $postUrl ?>"  <?php echo $postLinkAttr; ?> title="<?php echo $_post->getTitle(); ?>"><?php echo $_post->getTitle(); ?></a>
						<?php } ?>
					</div>
					<?php } ?>
					<?php if($show_author){ ?>
				<div class="post-author">
					<?php $author = $helper->getPostAuthor($_post);?>
					<i class="fa fa-user"></i> <a href="<?php echo $helper->getAuthorUrl($author); ?>" title="<?php echo $author->getNickName() ?>"><?php echo $author->getNickName() ?></a>
				</div>
				<?php } ?>
					<?php if($show_createdtime || $show_updatedtime){ ?>
					<div class="post-date">
						<?php if($show_createdtime){ ?>
						<?php $createdTime = $helper->getFormatDate($_post->getCreationTime(), $dateFormat); ?>
						<span><?php echo __('Created on %1', $createdTime); ?></span>
						<?php } ?>
						<?php if($show_updatedtime){ ?>
						<?php $updateTime = $helper->getFormatDate($_post->getUpdateTime(), $dateFormat); ?>
						<span><?php echo __('Updated on %1', $updateTime); ?></span>
						<?php } ?>
					</div>
					<?php } ?>
					<?php if($show_commentcount){ ?>
					<div class="post-comment">
						<?php echo __('%1 comments', $_post->getCommentCount()); ?>
					</div>
					<?php } ?>
					<?php if($show_categories){ ?>
					<div class="post-categories">
						<?php echo __('Pubslished In: ') ?>
						<?php
						$categories = $_post->getData('categories');
						$count = count($categories);
						?>
						<?php foreach ($categories as $k => $v) { ?>
						<a href="<?php echo $helper->getCategoryUrl($v['identifier'])  ?>" title="<?php echo $v['name'] ?>"><?php echo $v['name'] ?></a>
						<?php if(isset($categories[$k+1])) echo __(', '); ?>
						<?php } ?>
					</div>
					<?php } ?>
					<?php if($show_hits){ ?>
					<div class="post-hits"><span><?php echo __("Read");?></span> <strong><?php echo (int)$_post->getHits(); ?></strong> <?php echo __("Times"); ?></div>
					<?php } ?>
					<?php if($show_tags){ ?>
					<?php $tags = $_post->getTags(); ?>
					<?php if(!empty($tags)){ ?>
					<div class="post-tag">
						<span><?php echo __('Tags:'); ?></span>
						<?php foreach ($tags as $k => $v) { ?>
						<a href="<?php echo $helper->getTagUrl($v['alias']) ?>"><?php echo $v['name'] ?></a>
						<?php if(isset($tags[$k+1])) echo __(', '); ?>
						<?php } ?>
					</div>
					<?php } ?>
					<?php } ?>
					<?php if($show_shortdescription){ ?>
					<div class="post-summary">
						<?php $shortContent = $_post->getShortContent(); ?>
						<?php echo $helper->subString($shortContent, (int)$shortdescription_count); ?>
						<?php if($show_readmorelink){ ?>
						<a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr; ?> title="<?php echo $_post->getTitle(); ?>"><?php echo __('Read more') ?></a>
						<?php } ?>	
					</div>
					<?php } ?>
				</div>
			</li>
			<?php $i++; ?>
			<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>
