<?php
$_post = $this->getPost();
$helper = $this->helper("Ves\Blog\Helper\Data");
$imageHelper = $this->helper("Ves\Blog\Helper\Image");

/** General Settings **/
$dateFormat         = $helper->getConfig("general_settings/dateformat");
$twitterUsername    = $helper->getConfig("general_settings/twitter_username");
$enableNetworks     = $helper->getConfig("general_settings/enable_networks");
$addthis_pubid     = $helper->getConfig("general_settings/addthis_pubid");
$addthis_pubid 		= $addthis_pubid?$addthis_pubid:'ra-56ceab198f4f2e81';
$networks           = array_flip(explode(",", $helper->getConfig("general_settings/networks")));

/** POST Settings **/
$show_likedisklike   = $helper->getConfig("post_page/show_likedisklike");
$show_authorprofile  = $helper->getConfig("post_page/show_authorprofile");
$show_image          = $helper->getConfig("post_page/show_image");
$image_width         = (int)$helper->getConfig("post_page/image_width");
$image_height        = (int)$helper->getConfig("post_page/image_height");
$show_title          = $helper->getConfig("post_page/show_title");
$show_categories     = $helper->getConfig("post_page/show_categories");
$show_author         = $helper->getConfig("post_page/show_author");
$show_commentcount   = $helper->getConfig("post_page/show_commentcount");
$disable_comment 	 = $helper->getConfig('general_settings/disable_comment');
if($disable_comment) {
	$show_commentcount = false;
}
$show_updatedtime    = $helper->getConfig("post_page/show_updatedtime");
$show_createdtime    = $helper->getConfig("post_page/show_createdtime");
$show_hits           = $helper->getConfig("post_page/show_hits");
$show_tags           = $helper->getConfig("post_page/show_tags");
$show_socialnetworks           = $helper->getConfig("post_page/show_socialblock");
$_post->setData('categories', $_post->getPostCategories());
?>
<?php $postUrl = $helper->getPostUrl($_post); ?>
<div class="post-content-wrap">
	<?php if($show_image){ ?>
	<div class="post-image">
		<?php if( $_post->getImageType() == 1 && $_post->getImage()!=''){ ?>
		<?php if($image_width>0 && $_post->getThumbnail()){ ?>
		<img src="<?php echo $imageHelper->resizeImage($_post->getImage(), $image_width, $image_height) ?>" height="<?php echo $image_height ?>" width="<?php echo $image_width ?>" alt="<?php echo $_post->getTitle(); ?>"/>
		<?php }else{ ?>
		<img src="<?php echo $helper->getMediaUrl($_post->getImage()) ?>" alt="<?php echo $_post->getTitle(); ?>"/>
		<?php } ?>
		<?php }else if($_post->getImageType() == 2){ ?>
		<?php if($_post->getImageVideoType()==1 && $_post->getImageVideoId()!=''){ ?>
		<iframe src="https://www.youtube.com/embed/<?php echo $_post->getImageVideoId() ?>" frameborder="0" allowfullscreen height="<?php echo $image_height?$image_height:'500' ?>" width="<?php echo $image_width?$image_width:'100%' ?>"></iframe>
		<?php }else if($_post->getImageVideoType()==2 && $_post->getImageVideoId()!=''){ ?>
		<iframe src="https://player.vimeo.com/video/<?php echo $_post->getImageVideoId() ?>?color=3498DB&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen height="<?php echo $image_height?$image_height:'500' ?>" width="<?php echo $image_width?$image_width:'100%' ?>"></iframe>
		<?php } ?>
		<?php } ?>
	</div>
	<?php } ?>
	<div class="post-maincontent-wrapper">
		<div class="post-meta">
			<?php if($show_title){ ?>
			<div class="post-title">
				<h1><?php echo $_post->getTitle(); ?></h1>
			</div>
			<?php } ?>
			<?php if($show_author){ ?>
			<div class="post-author">
				<?php $author = $helper->getPostAuthor($_post); ?>
				<?php if($author) { ?>
				<i class="fa fa-user"></i> <a href="<?php echo $helper->getAuthorUrl($author); ?>" title="<?php echo $author->getNickName() ?>"><?php echo $author->getNickName() ?></a>
				<?php } ?>
			</div>
			<?php } ?>
			<?php if($show_createdtime || $show_updatedtime){ ?>
			<div class="post-date">
				<?php if($show_createdtime){ ?>
				<?php $createdTime = $helper->getFormatDate($_post->getCreationTime(), $dateFormat); ?>
				<i class="fa fa-clock-o"></i> <span><?php echo $createdTime; ?></span>
				<?php } ?>
				<?php if($show_updatedtime){ ?>
				<?php $updateTime = $helper->getFormatDate($_post->getUpdateTime(), $dateFormat); ?>
				<i class="fa fa-clock-o"></i> <span><?php echo $createdTime; ?></span>
				<?php } ?>
			</div>
			<?php } ?>
			<?php if($show_categories){ ?>
			<div class="post-categories">
				<i class="fa fa-folder"></i>
				<?php
				$categories = $_post->getPostCategories();
				$count = count($categories);
				?>
				<?php foreach ($categories as $k => $v) { ?>
				<a href="<?php echo $helper->getCategoryUrl($v['identifier'])  ?>" title="<?php echo $v['name'] ?>"><?php echo $v['name'] ?></a>
				<?php if(isset($categories[$k+1])) echo __(', '); ?>
				<?php } ?>
			</div>
			<?php } ?>
			<?php if($show_commentcount){ ?>
			<div class="post-comment">
				<i class="fa fa-comments"></i> <a href="<?php echo $postUrl ?>#comments"><?php echo $_post->getCommentCount(); ?></a>
			</div>
			<?php } ?>
			<?php if($show_hits){ ?>
			<div class="post-hits"><i class="fa fa-eye"></i> <span><?php echo (int)$_post->getHits(); ?></span></div>
			<?php } ?>
		</div>
		<div class="post-content">
			<?php echo $helper->filter($_post->getContent()) ?>
		</div>
	</div>
</div>
<?php if($show_likedisklike){ ?>
<div id="post-like" class="post-like">
	<a href="#" class="vbtn-like"><?php echo __('Like <span>(%1)</span>', (int)$_post->getLike()); ?></a>
	<a href="#" class="vbtn-disklike"><?php echo __('Disklike <span>(%1)</span>', (int)$_post->getDisklike()); ?></a>
	<div class="post-message"></div>
	<script type="text/javascript">
	require(['jquery'], function($){
		jQuery(document).ready(function($) {
			$('.post-like a').click(function(){
				var self = $(this);
				var like = 0;
				if($(this).hasClass('vbtn-like')){
					like = 1;
				}
				var tmp = '';
				$.ajax({
					url: '<?php echo $block->getUrl('vesblog/vote/post') ?>',
					type: 'post',
					data: { like: like, postId: <?php echo $_post->getId() ?> },
					dataType: 'json',
					beforeSend: function() {
						tmp = $(self).find('span').html();
						$(self).find('span').html('(...)');
					},
					success: function(result) {
						if(result.status){
							$('.post-like .post-message').addClass('post-success');
						}else{
							$('.post-like .post-message').addClass('post-error');
						}
						if(result.like) $('.post-like .vbtn-like span').html('(' + result.like + ')');
						if(result.disklike) $('.post-like .vbtn-disklike span').html('(' + result.disklike + ')');
						if(result.status == 0){
							$(self).find('span').html(tmp);
							tmp = '';
						}
						$('.post-like .post-message').html(result.message);
						setTimeout(function(){
							$('.post-like .post-message').html('');
							$('.post-like .post-message').removeClass('post-success').removeClass('post-error');							
						},2000);
					}
				});
				return false;
			});
		});
	});
	</script>
</div>
<?php } ?>
<div class="post-meta-bottom">
	<?php if($show_tags){ ?>
	<?php $tags = $_post->getPostTags(); ?>
	<?php if(!empty($tags)){ ?>
	<div class="post-tag">
		<span><?php echo __('Tags:'); ?></span>
		<?php foreach ($tags as $k => $v) { ?>
		<?php if(trim($v['name'])!=''){ ?>
		<a href="<?php echo $helper->getTagUrl($v['alias']) ?>"><?php echo $v['name'] ?></a>
		<?php } ?>
		<?php } ?>
	</div>
	<?php } ?>
	<?php } ?>
	<?php if($show_socialnetworks && $networks){ ?>
	<div class="post-social post-bottom">
		<span class="td-post-share-title"><?php echo __('SHARE'); ?></span>
		<!-- Go to www.addthis.com/dashboard to customize your tools -->
		<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
			<?php if(isset($networks['facebook'])){ ?>
			<a class="addthis_button_facebook"></a>
			<?php } ?>
			<?php if(isset($networks['twitter'])){ ?>
			<a class="addthis_button_twitter"></a>
			<?php } ?>
			<?php if(isset($networks['googleplus'])){ ?>
			<a class="addthis_button_google"></a>
			<?php } ?>
			<?php if(isset($networks['email'])){ ?>
			<a class="addthis_button_email"></a>
			<?php } ?>
			<?php if(isset($networks['pinterest'])){ ?>
			<a class="addthis_button_pinterest_share"></a>
			<?php } ?>
			<?php if(isset($networks['compact'])){ ?>
			<a class="addthis_button_compact"></a>
			<?php } ?>
		</div>
	</div>
	<?php } ?>
</div>
<?php if($show_socialnetworks && $networks){ ?>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $addthis_pubid; ?>"></script>
<?php } ?>

<?php if($show_authorprofile && isset($author) && $author){ ?>
<div id="author-box">
	<div class="block-title"><h2><strong><?php echo __('Author'); ?></strong></h2></div>
	<div class="block-content">
		<?php if($avatar = $author->getAvatar()){ ?>
		<div class="author-avatar">
		<a href="<?php echo $helper->getAuthorUrl($author); ?>" title="<?php echo $author->getNickName() ?>">
			<img src="<?php echo $imageHelper->resizeImage($avatar, 125, 125) ?>" alt="" height="125" width="125">
		</a>
		</div>
		<?php } ?>
		<h3 style="margin-top: 0;"><?php echo $author->getNickName(); ?></h3>
		<?php if($bio = $author->getDescription()){ ?>
		<div class="author-description"><?php echo $helper->filter($bio) ?></div>
		<?php } ?>

		<?php $authorSocials = unserialize($author->getSocialNetworks()); ?>
		<?php if(!empty($authorSocials)){ ?>
		<div class="author-social flat-social">
			<?php foreach ($authorSocials as $k => $v) { ?>
				<?php if(trim($v)!=''){ ?>
				<a class="social-<?php echo $k ?>" href="<?php echo $v; ?>"><i class="fa fa-<?php echo $k ?>"></i></a>
				<?php } ?>
			<?php } ?>
		</div>
		<?php } ?>
	</div>
</div>
<?php } ?>
<?php echo $this->getChildHtml("posts_related"); ?>
<?php echo $this->getChildHtml("posts_nextprev"); ?>
<?php echo $this->getChildHtml("products_related"); ?>
<?php if($_post->getEnableComment()){ ?>
<?php echo $this->getChildHtml("post_comment"); ?>
<?php } ?>