<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>


<!-- Navigation Bar -->
         
<nav class="navigation nav-bar" data-action="navigation">
     
            <div class="wrapper">
               <div class="medium-down--hide" style="float: left; width: 100%; position: relative;">
                  <div class="shop-by-collections">
                     <div class="sidebar-collections coll-hover">
                        <div class="sdcollections-title sb-title">
                           <span>Staples</span>
                        </div>
                        <div class="sdcollections-content">
                           <ul class="sdcollections-list">
                              <li class="sdc-element vetical-menu1 site-nav--has-dropdown" aria-haspopup="true">
                                 <a href="http://52.0.13.51/staple/aata.html" class="site-nav__link">
                                    <div class="element-main">
                                       <div class="collection-area have-icons">
                                          <div class="collection-name">
                                             Atta &amp; Other Flours
                                          </div>
                                       </div>
                                    </div>
                                 </a>
                                 <div  class="site-nav__dropdown vetical__dropdown vetical__dropdown1">
                                    <h2 class="heading-menu">Featured</h2>
                                    <ul>
                                       <li class="nav-links nav-links01 grid__item one-third">
                                          <ul>
                                             <li class="list-product text-center">
                                                <div class="list-product-image">
                                                   <a href="#"><img src="http://52.0.13.51/images/dropdown.png" alt="product"></a>
                                                </div>
                                                <div class="list-product-name mt-2">
                                                   Weekend Discount 40%
                                                </div>
                                                <div>Lorem Ipsum Totem</div>
                                             </li>
                                          </ul>
                                       </li>
                                       <li class="grid__item one-third text-center">
                                          <ul>
                                             <li class="list-product">
                                                <div class="list-product-image">
                                                   <a href="http://52.0.13.51/staple/.html"><img src="http://52.0.13.51/images/dropdown.png" alt="product"></a>
                                                </div>
                                                <div class="list-product-name mt-2">
                                                   Weekend Discount 40%
                                                </div>
                                                <div>Lorem Ipsum Totem</div>
                                             </li>
                                          </ul>
                                       </li>
                                       <li class="grid__item one-third text-center">
                                          <ul>
                                             <li class="list-product">
                                                <div class="list-product-image">
                                                   <a href="#"><img src="http://52.0.13.51/images/dropdown.png" alt="product"></a>
                                                </div>
                                                <div class="list-product-name mt-2">
                                                   Weekend Discount 40%
                                                </div>
                                                <div>Lorem Ipsum Totem</div>
                                             </li>
                                          </ul>
                                       </li>
                                    </ul>
                                 </div>
                              </li>
                              <li class="sdc-element vetical-menu2 site-nav--has-dropdown" aria-haspopup="true">
                                 <a href="#" class="site-nav__link">
                                    <div class="element-main">
                                       <div class="collection-area have-icons">
                                          <div class="collection-name">
                                             Rice &amp; Rice Products
                                          </div>
                                       </div>
                                    </div>
                                 </a>
                                 <div  class="site-nav__dropdown vetical__dropdown vetical__dropdown1">
                                    <h2 class="heading-menu">Featured</h2>
                                    <ul>
                                       <li class="nav-links nav-links01 grid__item one-third">
                                          <ul>
                                             <li class="list-product text-center">
                                                <div class="list-product-image">
                                                   <a href="#"><img src="http://52.0.13.51/images/dropdown.png" alt="product"></a>
                                                </div>
                                                <div class="list-product-name mt-2">
                                                   Weekend Discount 40%
                                                </div>
                                                <div>Lorem Ipsum Totem</div>
                                             </li>
                                          </ul>
                                       </li>
                                       <li class="grid__item one-third text-center">
                                          <ul>
                                             <li class="list-product">
                                                <div class="list-product-image">
                                                   <a href="#"><img src="http://52.0.13.51/images/dropdown.png" alt="product"></a>
                                                </div>
                                                <div class="list-product-name mt-2">
                                                   Weekend Discount 40%
                                                </div>
                                                <div>Lorem Ipsum Totem</div>
                                             </li>
                                          </ul>
                                       </li>
                                       <li class="grid__item one-third text-center">
                                          <ul>
                                             <li class="list-product">
                                                <div class="list-product-image">
                                                   <a href="#"><img src="http://52.0.13.51/images/dropdown.png" alt="product"></a>
                                                </div>
                                                <div class="list-product-name mt-2">
                                                   Weekend Discount 40%
                                                </div>
                                                <div>Lorem Ipsum Totem</div>
                                             </li>
                                          </ul>
                                       </li>
                                    </ul>
                                 </div>
                              </li>
                           </ul>
                        </div>
                     </div>
                     <script type="text/javascript">
                        $(function () {
                            $( ".sidebar-collections" ).hover(
                              function() {
                                $( this ).addClass( "coll-hover" );
                              }, function() {
                                $( this ).removeClass( "coll-hover" );
                              }
                            );
                            $(".sidebar-collections .sdcollections-title").click(function(){
                              $(this).toggleClass('opendrop');
                            });
                        });
                     </script>
                  </div>
                  <ul class="site-nav" id="AccessibleNav">
                     <li>
                        <a href="#" class="site-nav__link">
                        <span>Spices</span>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="site-nav__link">
                        <span>Cooking Oils</span>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="site-nav__link">
                        <span>Snacks</span>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="site-nav__link">
                        <span>Ready to Eat</span>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="site-nav__link">
                        <span>Breads</span>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="site-nav__link">
                        <span>Packaged Foods</span>
                        </a>
                     </li>
                     <li>
                        <a href="#" class="site-nav__link">
                        <span>Beverage</span>
                        </a>
                     </li>
                  </ul>
                  <!-- begin site-nav -->
                  <script>
                     $(window).ready(function($) {
                     //$('.megamenu__dropdown').css("width",$('#main-header').innerWidth());
                     });
                     $( window ).resize(function() {
                     //$('.megamenu__dropdown').css("width",$('#main-header').innerWidth());
                     });
                  </script>
               </div>
            </div>
         
</nav>
