<?php
$collection = $this->getCollection();
$helper     = $this->helper("Ves\Blog\Helper\Data");
$title      = $helper->getConfig('sidebar/categoriesblock_title');
$id         = rand() . time();
$html       = $block->drawItem($collection);
?>
<div class="ves-block block blog-cats">
	<?php if($title){ ?>
	<div class="block-title">
		<strong><?php echo $title ?></strong>
	</div>
	<?php } ?>
	<div class="block-content blog-widget-content">
		<ul id="blog-cats<?php echo $id ?>" class="blog-cats">
		<?php echo $block->getCategoryHtml(); ?>
		</ul>
		<script type="text/javascript">
		require([
			'jquery',
			<?php if($this->helper("Ves\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
            "Ves_All/lib/bootstrap/js/bootstrap.min"
             <?php endif; ?>
			], function(){
			jQuery(document).ready(function($){
				$('#blog-cats<?php echo $id ?> .opener').on('click', function(e) {
					e.preventDefault();
					var parent = $(this).parents("li").eq(0);
					$(this).toggleClass('item-active');
					$(parent).find(".children").eq(0).slideToggle();
					return false;
				});

			});
		});
		</script>
	</div>
</div>