<?php
$collection  = $this->getCollection();
$helper      = $this->helper("Ves\Blog\Helper\Data");
$imageHelper = $this->helper("Ves\Blog\Helper\Image");

/** General Settings **/
$dateFormat      = $helper->getConfig("general_settings/dateformat");
$twitterUsername = $helper->getConfig("general_settings/twitter_username");
$enableNetworks  = $helper->getConfig("general_settings/enable_networks");
$networks        = array_flip(explode(",", $helper->getConfig("general_settings/networks")));

/** Post Settings **/
$show_image             = $this->getConfig("product_page/show_image");
$image_width            = (int)$this->getConfig("product_page/image_width");
$image_height           = (int)$this->getConfig("product_page/image_height");
$show_title             = $this->getConfig("product_page/show_title");
$show_shortdescription  = $this->getConfig("product_page/show_shortdescription");
$shortdescription_count = $this->getConfig("product_page/shortdescription_count");
$show_readmorelink      = $this->getConfig("product_page/show_readmorelink");
$show_categories        = $this->getConfig("product_page/show_categories");
$show_author            = $this->getConfig("product_page/show_author");
$show_commentcount      = $this->getConfig("product_page/show_commentcount");
$disable_comment 		= $this->getConfig('general_settings/disable_comment');
if($disable_comment) {
	$show_commentcount = false;
}
$show_updatedtime       = $this->getConfig("product_page/show_updatedtime");
$show_createdtime       = $this->getConfig("product_page/show_createdtime");
$show_hits              = $this->getConfig("product_page/show_hits");
$show_tags              = $this->getConfig("product_page/show_tags");
$show_socialnetworks    = $this->getConfig("product_page/show_socialnetwork");
$item_height            = (int)$this->getConfig("product_page/item_height");


/** Owl Carousel Settings **/
$number_item_percolumn = $this->getConfig("product_page/number_item_percolumn", 1);
$large_max_items       = $this->getConfig("product_page/large_max_items", 4);
$large_items           = $this->getConfig("product_page/large_items", 4);
$portrait_items        = $this->getConfig("product_page/portrait_items", 3);
$tablet_items          = $this->getConfig("product_page/tablet_items", 3);
$tablet_small_items    = $this->getConfig("product_page/tablet_small_items", 2);
$mobile_items          = $this->getConfig("product_page/mobile_items", 1);
$rtl                   = $this->getConfig("product_page/rtl");
$autoplay              = $this->getConfig("product_page/autoplay");
$autoplay_timeout      = $this->getConfig("product_page/autoplay_timeout");
$autoplay_hoverpause   = $this->getConfig("product_page/autoplay_hoverpause");
$dots                  = $this->getConfig("product_page/dots");
$nav                   = $this->getConfig("product_page/nav");
$nav_prev              = str_replace("'", '"', $this->getConfig("product_page/nav_prev"));
$nav_next              = str_replace("'", '"', $this->getConfig("product_page/nav_next"));
$loop                  = $this->getConfig("product_page/loop");

$i = 1;
$x = 0;
$total = $collection->count();

if($total%$number_item_percolumn == 0){
	$column = $total/$number_item_percolumn;
}else{
	$column = floor($total/$number_item_percolumn)+1;
}

$_postCollection = [];
$i = $x = 0;
foreach ($collection as $_post) {
	if($i<$column){
		$i++;
	}else{
		$i = 1;
		$x++;
	}
	$_postCollection[$i][$x] = $_post;
}

$blockId = 'block' . time().rand();
$carousel = '';

$classes = 'owl-carousel owl-theme';
$carousel .= 'data-items="'.$number_item_percolumn.'"';
$carousel .= 'data-rtl="';
	$carousel .= $rtl?"true":"false";
$carousel .= '"';
$carousel .= 'data-autoplay="';
	$carousel .= $autoplay?"true":"false";
$carousel .= '"';
$carousel .= 'data-autoplay-timeout="';
	$carousel .= $autoplay_timeout;
$carousel .= '"';
$carousel .= 'data-dots="';
	$carousel .= $dots?"true":"false";
$carousel .= '"';
$carousel .= 'data-loop="';
	$carousel .= $loop?"true":"false";
$carousel .= '"';
$carousel .= 'data-nav = "';
	$carousel .= $nav?"true":"false";
$carousel .= '"';	
$carousel .= 'data-autoplay-pauonhover="';
$carousel .= $autoplay_hoverpause?"true":"false";
$carousel .= '"';
$carousel .= 'data-mobile-items="'.$mobile_items.'"';
$carousel .= 'data-tablet-small-items="'.$tablet_small_items.'"';
$carousel .= 'data-tablet-items="'.$tablet_items.'"';
$carousel .= 'data-portrait-items="'.$portrait_items.'"';
$carousel .= 'data-large-items="'.$large_items.'"';
$carousel .= 'data-large-max-items="'.$large_max_items.'"';

?>
<?php if(!empty($_postCollection)){ ?>
<div class="block ves-blog post-list postsstyle-style4 postsgrid1 blog-widget related-posts blog-posts">
	<div class="block-title">
		<h2><strong><?php echo __('Related Posts'); ?></strong></h2>
	</div>
	<div class="block-content blog-grid" <?php if($border_color = $this->getConfig('border_color')){ echo 'style="border-bottom-color: ' . $border_color . '"'; } ?>>
		<?php if($total>0){ ?>
		<ul id="<?php echo $blockId ?>" class="owl-carousel owl-theme" <?php echo $carousel; ?>>
			<?php foreach ($_postCollection as $_columnCollection) { ?>
			<li class="ves-post">
				<?php
				$y = 0;
				?>
				<?php foreach ($_columnCollection as $_post){ ?>
				<?php $postUrl = $helper->getPostUrl($_post); ?>
				<?php $postLinkAttr = $helper->getPostUrlLinkAttr($_post); ?>
				<?php
				$style = '';
				if($item_height>0){
					$style = 'style="height:' . $item_height . 'px"';
				}
				?>
				<div class="ves-post post-item" <?php echo $style; ?>>
					<div class="post-wrapper">
						<?php if($show_image){ ?>
						<?php $imageClass = ''; ?>
						<?php if($_post->getImageType() == 2 && $_post->getImageVideoId()!=''){
							$imageClass = ' post-video';
						} ?>
						<div class="post-image <?php echo $imageClass; ?>">
							<a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>">
								<?php if( $_post->getThumbnailType() == 1 && $_post->getPostThumbnail()!=''){ ?>
								<?php if($_post->getImageType() == 2 && $_post->getImageVideoId()!=''){ ?>
								<span class="fa overlay-icon"></span>
								<?php }else{ ?>
								<span class="fa overlay-icon"></span>
								<?php } ?>
								<?php if($image_width>0){ ?>
								<img src="<?php echo $imageHelper->resizeImage($_post->getPostThumbnail(), $image_width, $image_height) ?>" height="<?php echo $image_height ?>" width="<?php echo $image_width ?>" alt="<?php echo $_post->getTitle(); ?>"/>
								<?php }else{ ?>
								<img src="<?php echo $helper->getMediaUrl($_post->getPostThumbnail()) ?>" alt="<?php echo $_post->getTitle(); ?>"/>
								<?php } ?>
								<?php }else if($_post->getThumbnailType() == 2){ ?>
								<?php if($_post->getThumbnailVideoType()==1 && $_post->getThumbnailVideoId()!=''){ ?>
								<iframe width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" src="https://www.youtube.com/embed/<?php echo $_post->getThumbnailVideoId() ?>" frameborder="0" allowfullscreen></iframe>
								<?php }else if($_post->getThumbnailVideoType()==2 && $_post->getThumbnailVideoId()!=''){ ?>
								<iframe src="https://player.vimeo.com/video/<?php echo $_post->getThumbnailVideoId() ?>?color=3498DB&title=0&byline=0&portrait=0" width="<?php echo $image_width ?>" height="<?php echo $image_height ?>" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
								<?php } ?>
								<?php } ?>
							</a>
						</div>
						<?php } ?>

						<?php if($show_title){ ?>
						<div class="post-title">
						<h3><a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>"><?php echo $_post->getTitle(); ?></a></h3>
						</div>
						<?php } ?>
						<?php if($show_socialnetworks){ ?>
						<div class="post-socials">
							<div class="addthis_toolbox addthis_default_style" data-title="<?php echo $_post->getTitle(); ?>" addthis:url="<?php echo $postUrl ?>">
								<a class="addthis_button_facebook"></a>
								<a class="addthis_button_twitter"></a>
								<a class="addthis_button_google"></a>
								<a class="addthis_button_email"></a>
								<a class="addthis_button_pinterest_share"></a>
								<a class="addthis_button_compact"></a>
							</div>
						</div>
						<?php } ?>
						<div class="post-meta">
							<?php if($show_author){ ?>
							<div class="post-author">
								<?php if($author = $helper->getPostAuthor($_post)){ ?>
								<i class="fa fa-user"></i> <a href="<?php echo $helper->getAuthorUrl($author); ?>" title="<?php echo $author->getNickName() ?>"><?php echo $author->getNickName() ?></a>
								<?php } ?>
							</div>
							<?php } ?>
							<?php if($show_createdtime || $show_updatedtime){ ?>
							<div class="post-date">
								<?php if($show_createdtime){ ?>
								<?php $createdTime = $helper->getFormatDate($_post->getCreationTime(), $dateFormat); ?>
								<i class="fa fa-clock-o"></i> <span><?php echo $createdTime; ?></span>
								<?php } ?>
								<?php if($show_updatedtime){ ?>
								<?php $updateTime = $helper->getFormatDate($_post->getUpdateTime(), $dateFormat); ?>
								<i class="fa fa-clock-o"></i> <span><?php echo __('Updated on %1', $updateTime); ?></span>
								<?php } ?>
							</div>
							<?php } ?>
							<?php if($show_categories){ ?>
							<div class="post-categories">
								<?php
								$categories = $_post->getData('categories');
								$count = count($categories);
								?>
								<i class="fa fa-folder"></i> 
								<?php foreach ($categories as $k => $v) { ?>
								<a href="<?php echo $helper->getCategoryUrl($v['identifier'])  ?>" title="<?php echo $v['name'] ?>"><?php echo $v['name'] ?></a>
								<?php if(isset($categories[$k+1])) echo __(', '); ?>
								<?php } ?>
							</div>
							<?php } ?>
							<?php if($show_hits){ ?>
							<div class="post-hits"><i class="fa fa-eye"></i> <span><?php echo (int)$_post->getHits(); ?></span></div>
							<?php } ?>
							<?php if($show_commentcount){ ?>
							<div class="post-comment">
								<i class="fa fa-comments"></i> <a href="<?php echo $postUrl ?>#comments" <?php echo $postLinkAttr;?>><?php echo $_post->getCommentCount(); ?></a>
							</div>

							<?php } ?>
						</div>
						<?php if($show_tags){ ?>
						<?php $tags = $_post->getTag(); ?>
						<?php if(!empty($tags)){ ?>
						<div class="post-tag">
							<span><?php echo __('Tags:'); ?></span>
							<?php foreach ($tags as $k => $v) { ?>
							<a href="<?php echo $helper->getTagUrl($v['alias']) ?>"><?php echo trim($v['name']) ?></a>
							<?php if(isset($tags[$k+1])) echo __(', '); ?>
							<?php } ?>
						</div>
						<?php } ?>
						<?php } ?>
						<?php if($show_shortdescription){ ?>
						<div class="post-summary">
							<?php $shortContent = $_post->getShortContent(); ?>
							<?php echo $helper->subString($shortContent, (int)$shortdescription_count); ?>
						</div>
						<?php if($show_readmorelink){ ?>
						<div class="post-readmore"><a href="<?php echo $postUrl ?>" <?php echo $postLinkAttr;?> title="<?php echo $_post->getTitle(); ?>" ><?php echo __('Read more') ?> <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
						<?php } ?>
						<?php } ?>
					</div>
				</div>
				<?php $y++; ?>
				<?php } ?>
			</li>
			<?php } ?>
		</ul>
		<?php } ?>
		<script>
			require([
				'jquery'
				], function($){
					jQuery(document).ready(function() {
						var anchorColor = '';
						$('#<?php echo $blockId ?> a').hover(function(){
							anchorColor = '';
							if($(this).data('hover-color')!=''){
								$(this).css('color',$(this).data('hover-color'));
							}
						}, function(){
							$(this).css('color','');
						})
					});
				});
			</script>

			<?php if($show_socialnetworks){ ?>
			<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-56ceab198f4f2e81"></script>
			<?php } ?>
		</div>
	</div>
	<?php } ?>