<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $_total = $block->getItems()->getSize() ?>
<?php if ($_total): ?>
	<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
	<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
	<?php $size = $themeHelper->getImageMinSize(); ?>
    <?php $padding = $themeHelper->getImagePadding(); ?>
	
	<div class="text-right" style="padding-bottom: 30px;">
		<a href="#" class="action print btn-print" title="<?php /* @escapeNotVerified */ echo __('Print This Page') ?>">
			<i class="fa fa-print" aria-hidden="true"></i>
			<span><?php /* @escapeNotVerified */ echo __('Print This Page') ?></span>
		</a>
	</div>
        <div class="table-wrapper comparison">
            <table class="data table table-comparison" id="product-comparison"
                data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
                <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Compare Products') ?></caption>
                <thead>
                <tr>
                    <?php $_i = 0 ?>
                    <?php foreach ($block->getItems() as $_item): ?>
                        <?php if ($_i++ == 0): ?>
                            <th scope="row" class="cell remove"><span><?php /* @escapeNotVerified */ echo __('Remove Product') ?></span></th>
                        <?php endif; ?>
                        <td class="cell remove product text-center">
                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataRemove($_item); ?>'
                               class="action btn btn-primary btn-xs delete" title="<?php /* @escapeNotVerified */ echo __('Remove Product') ?>"><?php /* @escapeNotVerified */ echo __('Remove Product') ?></a>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <?php $_i = 0; ?>
                    <?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
                    <?php /** @var $_item \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($block->getItems() as $_item): ?>
                        <?php if ($_i++ == 0): ?>
                            <th scope="row" class="cell product"><span><?php /* @escapeNotVerified */ echo __('Product') ?></span></th>
                        <?php endif; ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Product')); ?>" class="cell product info">
							<div class="list-products">
								<div class="product-item-info">
									<div class="product-image">
										<?php $productImage = $_imagehelper->init($_item, 'product_comparison_list')->resize($size['width'], $size['height'])->getUrl(); ?>
										<a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>" style="padding-bottom: <?php echo $padding; ?>;overflow: hidden;">
											<img src="<?php echo $productImage ?>" alt="<?php echo $block->stripTags($_item->getName(), null, true) ?>" class="img-responsive product-image-photo">
										</a>
										
									</div>
									<div class="product-item-details">
										<h5 class="product-item-name">
											<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
												<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
											</a>
										</h5>
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item, '-compare-list-top') ?>
										<?php echo $block->getReviewsSummaryHtml($_item, 'short') ?>
										<div class="product-item-actions">
											<?php if ($_item->isSaleable()): ?>
												<div class="actions-primary">
													<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>" method="post">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit" class="action tocart btn btn-xs btn-default">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart'); ?></span>
														</button>
													</form>
												</div>
											<?php endif; ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <button data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action mgs-quickview towishlist btn btn-xs btn-default" data-action="add-to-wishlist"><span class="fa fa-heart-o"></span></button>
                                                </div>
                                            <?php endif; ?>
										</div>
									</div>
								</div>
							</div>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </tbody>
                <tbody>
                <?php foreach ($block->getAttributes() as $attribute) :?>
                    <?php $index = 0; ?>
                    <?php if ($block->hasAttributeValueForProducts($attribute)) :?>
                         <tr>
                            <?php foreach ($block->getItems() as $item) :?>
                                <?php if ($index++ == 0) :?>
                                    <th scope="row" class="cell label">
                                        <span class="attribute label">
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                        </span>
                                    </th>
                                <?php endif; ?>
                                <td class="cell product attribute">
                                    <div class="attribute value">
                                        <?php switch ($attribute->getAttributeCode()) {
                                            case "price": ?>
                                                <?=
                                                /* @noEscape */ $block->getProductPrice(
                                                    $item,
                                                    '-compare-list-' . $attribute->getCode()
                                                )
                                                ?>
                                                <?php break;
                                            case "small_image": ?>
                                                <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                                <?php break;
                                            default :?>
                                                <?php if (is_string($block->getProductAttributeValue($item, $attribute))) :?>
                                                    <?= /* @noEscape */ $_helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                                <?php else : ?>
                                                    <?=  $block->escapeHtml($_helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode())) ?>
                                                <?php endif; ?>
                                                <?php break;
                                        } ?>
                                    </div>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
        <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('You have no items to compare.') ?></div></div>
<?php endif; ?>
