<?php
/**
 * templates/default/jsWindow.phtml
 *
 * @copyright Copyright © 2021 Lof. All rights reserved.
 * @author    Lof
 * @category Lof
 * @copyright Copyright (c) 2014 Lof (<https://www.lof.com>)
 * @license <https://www.lof.com/license-agreement.html>
 * @Author: lof<support@lof.com>
 * @github: <https://github.com/lof>
 */
?>
<?php
$helper = $this->helper("Lof\RecentlyViewed\Helper\Data");
$lofRviewedEnable = $helper->getConfigModule("general/enabled");
?>
<script>
    window.lofRecentlyviewed = <?php echo $lofRviewedEnable; ?>;
</script>

