<script type="text/javascript">
if(document.getElementById('countdown-timer')){
    setInterval(function time(){ 
        var d = new Date();  
        var hours = 24 - d.getHours();  
        var min = 60 - d.getMinutes();  
        if((min + '').length == 1){    
            min = '0' + min;  
        }  
        var sec = 60 - d.getSeconds(); 
        if((sec + '').length == 1){        
            sec = '0' + sec;  
        }  
        document.getElementById('countdown-timer').innerHTML =hours+':'+min+':'+sec;
    }, 1000);
}

require(['jquery', 'Ves_All/lib/owl.carousel/owl.carousel.min'], function($) {
    var banner_owl = $("#slider2");
    if(banner_owl && banner_owl.length >0){
        banner_owl.owlCarousel({
            items: 1,
            autoplay: true,
            autoplayTimeout: 5000,
            autoplayHoverPause: true,
            dots: false,
            nav: true,
            navRewind: true,
            animateIn: 'fadeIn',
            animateOut: 'fadeOut',
            loop: true,
            navText: ["<span class='icon icon-557'> </span>", "<span class='icon icon-556'> </span>"]
        });
    }
});
</script>