<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
			<strong class="title" data-role="title"><?php echo __('Filter'); ?></strong>
        </div>
        <div class="block-content filter-content">
			<h3 class="close-filter-fixed">
				<button id="close-filter"><i class="close-filter pe-7s-close pa"></i></button>
			</h3>
			<div class="block-filter-content">
				<?php echo $block->getChildHtml('state') ?>

				<?php if ($block->getLayer()->getState()->getFilters()): ?>
					<div class="block-actions filter-actions">
						<a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action btn btn-xs btn-primary clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
					</div>
				<?php endif; ?>
				<?php $wrapOptions = false; ?>
				<?php foreach ($block->getFilters() as $filter): ?>
					<?php if ($filter->getItemsCount()): ?>
						<?php if (!$wrapOptions): ?>
							<div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
						<?php  $wrapOptions = true; endif; ?>
						<div data-role="collapsible" class="filter-options-item">
							<div data-role="title" class="filter-options-title"><?php echo __('Filter by %1', $filter->getName()); ?></div>
							<div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
						</div>
					<?php endif; ?>
					
				<?php endforeach; ?>
				<?php if ($wrapOptions): ?>
					</div>
				<?php else: ?>
					<script>
						require([
							'jquery'
						], function ($) {
							$('#layered-filter-block').addClass('filter-no-options');
                            // Closed filter fixed
                            $(document).on("click","#close-filter",function(e){
                                $('body').removeClass('filter-active');		
                            });
						});
					</script>
				<?php endif; ?>
			</div>
        </div>
        <script type="text/javascript">
            require([
                'jquery'
            ], function ($) {
                $(document).ready(function(){
                    $(document).on("click","#close-filter",function(e){
                        $('body').removeClass('filter-active');	
                    }); 
                }); 
            });
        </script>
    </div>
<?php endif; ?>
