<?php
$helper = $this->helper("Ves\Blog\Helper\Data");
$title = $helper->getConfig('sidebar/searchform_title');
?>
<div class="ves-block block blog-searchform">
	<?php if($title){ ?>
	<div class="block-title">
		<strong><?php echo __('Search Form'); ?></strong>
	</div>
	<?php } ?>
	<div class="block-content">
		<form method="get" class="search-form" action="<?php echo $helper->getSearchFormUrl(); ?>" data-mage-init='{"validation":{}}'>
			<input type="text" class="search-field required-entry" placeholder="<?php echo __('Search posts here…'); ?>" value="<?php echo $helper->getSearchKey() ?>" name="s" title="<?php echo __('Search for:'); ?>">
			<button type="submit" class="search-submit"><i class="fa fa-search"></i></button>
		</form>
	</div>
</div>