<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="block newsletter">
    <div class="content">
        <form class="form subscribe"
                novalidate
                action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                id="newsletter-popup-validate-detail">
            <?php if ($this->helper('MGS\Mpanel\Helper\Data')->getStoreConfig('mpanel/newsletter_popup/disable_form_newsletter')== 0): ?>
            <div class="field form-group newsletter">
                <div class="control">
                    <input name="email" type="email" id="newsletter-popup-email"
                                    placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                    data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions text-center">
                <button class="action subscribe btn btn-primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
            </div>
            <?php endif; ?>
    		<div class="checkbox text-center">
    			<label for="dont_show">
    				<input id="dont_show" onclick="dontShowPopup('dont_show')" type="checkbox">
    				<?php echo __("Don't show this popup again");  ?>
    			</label>
    		</div>
        </form>
    </div>
</div>
