<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$helper =  \Magento\Framework\App\ObjectManager::getInstance()->get('MGS\Mpanel\Helper\Data');
$url = $helper->getCssUrl();
$canUsePanel = $helper->acceptToUsePanel();
?>
<!doctype html>
<html class="use-<?php echo $helper->getHeaderClass() ?>" <?php /* @escapeNotVerified */ echo $htmlAttributes ?>>
    <head <?php /* @escapeNotVerified */ echo $headAttributes ?>>
        <script>
            var WEB_URL = "<?php echo $helper->getUrlBuilder()->getUrl() ?>";
            
            var CATALOG_AJAX = <?php echo $helper->getStoreConfig('mgstheme/general/catalog_ajax'); ?>
        </script>
        <?php /* @escapeNotVerified */ echo $requireJs ?>
        <?php /* @escapeNotVerified */ echo $headContent ?>
        <?php /* @escapeNotVerified */ echo $headAdditional ?>
        <?php echo $helper->getLinksFont() ?>
        <link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $url ?>" /> 
        <?php if($helper->showButton()): ?>
        <link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $helper->getPanelCssUrl() ?>" /> 
        <?php endif ?>
        
    </head>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?php /* @escapeNotVerified */ echo $loaderIcon; ?>"}}' <?php /* @escapeNotVerified */ echo $bodyAttributes ?>>
    
        <?php if($helper->useBuilder() && $helper->isHomepage()): ?>
            <div class="page messages container" style="display: none;">
                <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/messages.phtml")->toHtml(); ?>
                <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Messages")->setTemplate("Magento_Theme::messages.phtml")->toHtml(); ?>
            </div>
        <?php endif ?>
        
        <?php if($helper->showButton() && !$helper->isPopup()): ?>
            <?php echo $topPanel ?>
        <?php endif ?>
         <?php /* @escapeNotVerified */ echo $helper->convertContent($layoutContent, $builderContent) ?>
        
        <?php if($canUsePanel): ?>
            <script  type="text/javascript" src="<?php echo $this->getViewFileUrl('MGS_Mpanel::js/panel.js') ?>"></script>
        <?php endif ?>
        
        <?php if($helper->useBuilder() && $helper->isHomepage()): ?>
            <script  type="text/javascript">
                require([
                    'jquery'
                ], function(jQuery){
                    (function($) {
                        jQuery(document).ready(function(){
                            jQuery(".page.messages").appendTo(".header-placeholder");
                            jQuery(".page.messages").show();
                        });
                        jQuery(window).scroll(function(){
                            if($(this).scrollTop() > 200){
                                jQuery(".page.messages").hide();
                            }
                        })
                    })(jQuery);
                });
            </script>
        <?php endif ?>
    </body>
</html>
