<?php
$helper     = $this->helper("Ves\Blog\Helper\Data");
$collection = $this->getCollection();
$posts      = $this->getData("posts");
$dateFormat = $helper->getConfig("general_settings/dateformat");
$title      = $helper->getConfig('sidebar/recentcommentsblock_title');
?>
<?php if($collection->count()){ ?>
<div class="ves-block block blog-recentcomments">
	<?php if($title){ ?>
	<div class="block-title">
		<strong><?php echo $title ?></strong>
	</div>
	<?php } ?>
	<div class="block-content blog-widget-content">
		<ul>
			<?php foreach ($collection as $_comment) { ?>
			<?php if(!isset($posts[$_comment->getPostId()])) continue; ?>
			<?php $_post = $posts[$_comment->getPostId()]; ?>
			<li>
				<a href="<?php echo $helper->getPostUrl($_post) . '#comment' . $_comment->getCommentId()  ?>"><?php echo $_post->getTitle() ?></a>
				<div class="post-shortcontent"><?php echo $helper->subString($_comment->getContent(), 50); ?></div>
			</li>
			<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>