<?php $_productCollection = $this->getCategoryProductByIds($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<div class="content-block category-product-cat-block products-grid product-masonry-nopadding">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_title')): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if (count($_productCollection)>0): ?>
		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$perRow = $this->getPerrow();
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
		?>
		
		<div class="block widget mgs-products category-products-grid products-grid products-masonry">
			<div class="items" id="category-products<?php echo $blockId; ?>">
				<div class="row">
                    <?php foreach ($_productCollection as $_product): ?>
                        <div class="product product-item">
                            <?php echo $this->getLayout()
                                            ->createBlock('MGS\Mpanel\Block\Products\ProductItem')
                                            ->setProductId($_product->getId())
                                            ->setThemeHelper($themeHelper)
                                            ->setImageHelper($_imagehelper)
                                            ->setCatalogHelperOutput($_helper)
                                            ->setRatio($this->getRatio())
                                            ->setTemplate('MGS_Mpanel::products/grid_items_masonry.phtml')
                                            ->toHtml(); ?>
                                            
                        </div>
                    <?php endforeach; ?>
                </div>
			</div>
		</div>
		
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no products matching the selection.') ?></div>
	<?php endif ?>
</div>